// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: authlayer/v1/apikey.proto

package authlayerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type APIKeyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	KeyPrefix     string                 `protobuf:"bytes,3,opt,name=key_prefix,json=keyPrefix,proto3" json:"key_prefix,omitempty"`
	Scopes        []string               `protobuf:"bytes,4,rep,name=scopes,proto3" json:"scopes,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_used_at,json=lastUsedAt,proto3,oneof" json:"last_used_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIKeyInfo) Reset() {
	*x = APIKeyInfo{}
	mi := &file_authlayer_v1_apikey_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKeyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeyInfo) ProtoMessage() {}

func (x *APIKeyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_apikey_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeyInfo.ProtoReflect.Descriptor instead.
func (*APIKeyInfo) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_apikey_proto_rawDescGZIP(), []int{0}
}

func (x *APIKeyInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *APIKeyInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *APIKeyInfo) GetKeyPrefix() string {
	if x != nil {
		return x.KeyPrefix
	}
	return ""
}

func (x *APIKeyInfo) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *APIKeyInfo) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *APIKeyInfo) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

func (x *APIKeyInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Scopes        []string               `protobuf:"bytes,2,rep,name=scopes,proto3" json:"scopes,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAPIKeyRequest) Reset() {
	*x = CreateAPIKeyRequest{}
	mi := &file_authlayer_v1_apikey_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAPIKeyRequest) ProtoMessage() {}

func (x *CreateAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_apikey_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_apikey_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAPIKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAPIKeyRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *CreateAPIKeyRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type CreateAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        *APIKeyInfo            `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	PlainTextKey  string                 `protobuf:"bytes,2,opt,name=plain_text_key,json=plainTextKey,proto3" json:"plain_text_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAPIKeyResponse) Reset() {
	*x = CreateAPIKeyResponse{}
	mi := &file_authlayer_v1_apikey_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAPIKeyResponse) ProtoMessage() {}

func (x *CreateAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_apikey_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_apikey_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAPIKeyResponse) GetApiKey() *APIKeyInfo {
	if x != nil {
		return x.ApiKey
	}
	return nil
}

func (x *CreateAPIKeyResponse) GetPlainTextKey() string {
	if x != nil {
		return x.PlainTextKey
	}
	return ""
}

type RevokeAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKeyId      string                 `protobuf:"bytes,1,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAPIKeyRequest) Reset() {
	*x = RevokeAPIKeyRequest{}
	mi := &file_authlayer_v1_apikey_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAPIKeyRequest) ProtoMessage() {}

func (x *RevokeAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_apikey_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*RevokeAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_apikey_proto_rawDescGZIP(), []int{3}
}

func (x *RevokeAPIKeyRequest) GetApiKeyId() string {
	if x != nil {
		return x.ApiKeyId
	}
	return ""
}

type RevokeAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAPIKeyResponse) Reset() {
	*x = RevokeAPIKeyResponse{}
	mi := &file_authlayer_v1_apikey_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAPIKeyResponse) ProtoMessage() {}

func (x *RevokeAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_apikey_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*RevokeAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_apikey_proto_rawDescGZIP(), []int{4}
}

type ListAPIKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PaginationRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAPIKeysRequest) Reset() {
	*x = ListAPIKeysRequest{}
	mi := &file_authlayer_v1_apikey_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAPIKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAPIKeysRequest) ProtoMessage() {}

func (x *ListAPIKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_apikey_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAPIKeysRequest.ProtoReflect.Descriptor instead.
func (*ListAPIKeysRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_apikey_proto_rawDescGZIP(), []int{5}
}

func (x *ListAPIKeysRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListAPIKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKeys       []*APIKeyInfo          `protobuf:"bytes,1,rep,name=api_keys,json=apiKeys,proto3" json:"api_keys,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAPIKeysResponse) Reset() {
	*x = ListAPIKeysResponse{}
	mi := &file_authlayer_v1_apikey_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAPIKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAPIKeysResponse) ProtoMessage() {}

func (x *ListAPIKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_apikey_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAPIKeysResponse.ProtoReflect.Descriptor instead.
func (*ListAPIKeysResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_apikey_proto_rawDescGZIP(), []int{6}
}

func (x *ListAPIKeysResponse) GetApiKeys() []*APIKeyInfo {
	if x != nil {
		return x.ApiKeys
	}
	return nil
}

func (x *ListAPIKeysResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ValidateAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAPIKeyRequest) Reset() {
	*x = ValidateAPIKeyRequest{}
	mi := &file_authlayer_v1_apikey_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAPIKeyRequest) ProtoMessage() {}

func (x *ValidateAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_apikey_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*ValidateAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_apikey_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateAPIKeyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ValidateAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        *string                `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	Scopes        []string               `protobuf:"bytes,3,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAPIKeyResponse) Reset() {
	*x = ValidateAPIKeyResponse{}
	mi := &file_authlayer_v1_apikey_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAPIKeyResponse) ProtoMessage() {}

func (x *ValidateAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_apikey_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*ValidateAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_apikey_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateAPIKeyResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateAPIKeyResponse) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *ValidateAPIKeyResponse) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

var File_authlayer_v1_apikey_proto protoreflect.FileDescriptor

const file_authlayer_v1_apikey_proto_rawDesc = "" +
	"\n" +
	"\x19authlayer/v1/apikey.proto\x12\fauthlayer.v1\x1a\x19authlayer/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc5\x02\n" +
	"\n" +
	"APIKeyInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"key_prefix\x18\x03 \x01(\tR\tkeyPrefix\x12\x16\n" +
	"\x06scopes\x18\x04 \x03(\tR\x06scopes\x12>\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\texpiresAt\x88\x01\x01\x12A\n" +
	"\flast_used_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\n" +
	"lastUsedAt\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\r\n" +
	"\v_expires_atB\x0f\n" +
	"\r_last_used_at\"\x90\x01\n" +
	"\x13CreateAPIKeyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06scopes\x18\x02 \x03(\tR\x06scopes\x12>\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\texpiresAt\x88\x01\x01B\r\n" +
	"\v_expires_at\"o\n" +
	"\x14CreateAPIKeyResponse\x121\n" +
	"\aapi_key\x18\x01 \x01(\v2\x18.authlayer.v1.APIKeyInfoR\x06apiKey\x12$\n" +
	"\x0eplain_text_key\x18\x02 \x01(\tR\fplainTextKey\"3\n" +
	"\x13RevokeAPIKeyRequest\x12\x1c\n" +
	"\n" +
	"api_key_id\x18\x01 \x01(\tR\bapiKeyId\"\x16\n" +
	"\x14RevokeAPIKeyResponse\"U\n" +
	"\x12ListAPIKeysRequest\x12?\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1f.authlayer.v1.PaginationRequestR\n" +
	"pagination\"\x8c\x01\n" +
	"\x13ListAPIKeysResponse\x123\n" +
	"\bapi_keys\x18\x01 \x03(\v2\x18.authlayer.v1.APIKeyInfoR\aapiKeys\x12@\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2 .authlayer.v1.PaginationResponseR\n" +
	"pagination\")\n" +
	"\x15ValidateAPIKeyRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"p\n" +
	"\x16ValidateAPIKeyResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x1c\n" +
	"\auser_id\x18\x02 \x01(\tH\x00R\x06userId\x88\x01\x01\x12\x16\n" +
	"\x06scopes\x18\x03 \x03(\tR\x06scopesB\n" +
	"\n" +
	"\b_user_id2\xee\x02\n" +
	"\rAPIKeyService\x12U\n" +
	"\fCreateAPIKey\x12!.authlayer.v1.CreateAPIKeyRequest\x1a\".authlayer.v1.CreateAPIKeyResponse\x12U\n" +
	"\fRevokeAPIKey\x12!.authlayer.v1.RevokeAPIKeyRequest\x1a\".authlayer.v1.RevokeAPIKeyResponse\x12R\n" +
	"\vListAPIKeys\x12 .authlayer.v1.ListAPIKeysRequest\x1a!.authlayer.v1.ListAPIKeysResponse\x12[\n" +
	"\x0eValidateAPIKey\x12#.authlayer.v1.ValidateAPIKeyRequest\x1a$.authlayer.v1.ValidateAPIKeyResponseBJZHgithub.com/bernardoforcillo/authlayer/pkg/proto/authlayer/v1;authlayerv1b\x06proto3"

var (
	file_authlayer_v1_apikey_proto_rawDescOnce sync.Once
	file_authlayer_v1_apikey_proto_rawDescData []byte
)

func file_authlayer_v1_apikey_proto_rawDescGZIP() []byte {
	file_authlayer_v1_apikey_proto_rawDescOnce.Do(func() {
		file_authlayer_v1_apikey_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authlayer_v1_apikey_proto_rawDesc), len(file_authlayer_v1_apikey_proto_rawDesc)))
	})
	return file_authlayer_v1_apikey_proto_rawDescData
}

var file_authlayer_v1_apikey_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_authlayer_v1_apikey_proto_goTypes = []any{
	(*APIKeyInfo)(nil),             // 0: authlayer.v1.APIKeyInfo
	(*CreateAPIKeyRequest)(nil),    // 1: authlayer.v1.CreateAPIKeyRequest
	(*CreateAPIKeyResponse)(nil),   // 2: authlayer.v1.CreateAPIKeyResponse
	(*RevokeAPIKeyRequest)(nil),    // 3: authlayer.v1.RevokeAPIKeyRequest
	(*RevokeAPIKeyResponse)(nil),   // 4: authlayer.v1.RevokeAPIKeyResponse
	(*ListAPIKeysRequest)(nil),     // 5: authlayer.v1.ListAPIKeysRequest
	(*ListAPIKeysResponse)(nil),    // 6: authlayer.v1.ListAPIKeysResponse
	(*ValidateAPIKeyRequest)(nil),  // 7: authlayer.v1.ValidateAPIKeyRequest
	(*ValidateAPIKeyResponse)(nil), // 8: authlayer.v1.ValidateAPIKeyResponse
	(*timestamppb.Timestamp)(nil),  // 9: google.protobuf.Timestamp
	(*PaginationRequest)(nil),      // 10: authlayer.v1.PaginationRequest
	(*PaginationResponse)(nil),     // 11: authlayer.v1.PaginationResponse
}
var file_authlayer_v1_apikey_proto_depIdxs = []int32{
	9,  // 0: authlayer.v1.APIKeyInfo.expires_at:type_name -> google.protobuf.Timestamp
	9,  // 1: authlayer.v1.APIKeyInfo.last_used_at:type_name -> google.protobuf.Timestamp
	9,  // 2: authlayer.v1.APIKeyInfo.created_at:type_name -> google.protobuf.Timestamp
	9,  // 3: authlayer.v1.CreateAPIKeyRequest.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 4: authlayer.v1.CreateAPIKeyResponse.api_key:type_name -> authlayer.v1.APIKeyInfo
	10, // 5: authlayer.v1.ListAPIKeysRequest.pagination:type_name -> authlayer.v1.PaginationRequest
	0,  // 6: authlayer.v1.ListAPIKeysResponse.api_keys:type_name -> authlayer.v1.APIKeyInfo
	11, // 7: authlayer.v1.ListAPIKeysResponse.pagination:type_name -> authlayer.v1.PaginationResponse
	1,  // 8: authlayer.v1.APIKeyService.CreateAPIKey:input_type -> authlayer.v1.CreateAPIKeyRequest
	3,  // 9: authlayer.v1.APIKeyService.RevokeAPIKey:input_type -> authlayer.v1.RevokeAPIKeyRequest
	5,  // 10: authlayer.v1.APIKeyService.ListAPIKeys:input_type -> authlayer.v1.ListAPIKeysRequest
	7,  // 11: authlayer.v1.APIKeyService.ValidateAPIKey:input_type -> authlayer.v1.ValidateAPIKeyRequest
	2,  // 12: authlayer.v1.APIKeyService.CreateAPIKey:output_type -> authlayer.v1.CreateAPIKeyResponse
	4,  // 13: authlayer.v1.APIKeyService.RevokeAPIKey:output_type -> authlayer.v1.RevokeAPIKeyResponse
	6,  // 14: authlayer.v1.APIKeyService.ListAPIKeys:output_type -> authlayer.v1.ListAPIKeysResponse
	8,  // 15: authlayer.v1.APIKeyService.ValidateAPIKey:output_type -> authlayer.v1.ValidateAPIKeyResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_authlayer_v1_apikey_proto_init() }
func file_authlayer_v1_apikey_proto_init() {
	if File_authlayer_v1_apikey_proto != nil {
		return
	}
	file_authlayer_v1_common_proto_init()
	file_authlayer_v1_apikey_proto_msgTypes[0].OneofWrappers = []any{}
	file_authlayer_v1_apikey_proto_msgTypes[1].OneofWrappers = []any{}
	file_authlayer_v1_apikey_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authlayer_v1_apikey_proto_rawDesc), len(file_authlayer_v1_apikey_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authlayer_v1_apikey_proto_goTypes,
		DependencyIndexes: file_authlayer_v1_apikey_proto_depIdxs,
		MessageInfos:      file_authlayer_v1_apikey_proto_msgTypes,
	}.Build()
	File_authlayer_v1_apikey_proto = out.File
	file_authlayer_v1_apikey_proto_goTypes = nil
	file_authlayer_v1_apikey_proto_depIdxs = nil
}
