// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: authlayer/v1/organization.proto

package authlayerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrganizationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	OwnerId       string                 `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationInfo) Reset() {
	*x = OrganizationInfo{}
	mi := &file_authlayer_v1_organization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationInfo) ProtoMessage() {}

func (x *OrganizationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_organization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationInfo.ProtoReflect.Descriptor instead.
func (*OrganizationInfo) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_organization_proto_rawDescGZIP(), []int{0}
}

func (x *OrganizationInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrganizationInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrganizationInfo) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *OrganizationInfo) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *OrganizationInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrganizationRequest) Reset() {
	*x = CreateOrganizationRequest{}
	mi := &file_authlayer_v1_organization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationRequest) ProtoMessage() {}

func (x *CreateOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_organization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationRequest.ProtoReflect.Descriptor instead.
func (*CreateOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_organization_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrganizationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOrganizationRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type CreateOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organization  *OrganizationInfo      `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrganizationResponse) Reset() {
	*x = CreateOrganizationResponse{}
	mi := &file_authlayer_v1_organization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationResponse) ProtoMessage() {}

func (x *CreateOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_organization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationResponse.ProtoReflect.Descriptor instead.
func (*CreateOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_organization_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrganizationResponse) GetOrganization() *OrganizationInfo {
	if x != nil {
		return x.Organization
	}
	return nil
}

type GetOrganizationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*GetOrganizationRequest_Id
	//	*GetOrganizationRequest_Slug
	Identifier    isGetOrganizationRequest_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrganizationRequest) Reset() {
	*x = GetOrganizationRequest{}
	mi := &file_authlayer_v1_organization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationRequest) ProtoMessage() {}

func (x *GetOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_organization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationRequest.ProtoReflect.Descriptor instead.
func (*GetOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_organization_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrganizationRequest) GetIdentifier() isGetOrganizationRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *GetOrganizationRequest) GetId() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetOrganizationRequest_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *GetOrganizationRequest) GetSlug() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetOrganizationRequest_Slug); ok {
			return x.Slug
		}
	}
	return ""
}

type isGetOrganizationRequest_Identifier interface {
	isGetOrganizationRequest_Identifier()
}

type GetOrganizationRequest_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type GetOrganizationRequest_Slug struct {
	Slug string `protobuf:"bytes,2,opt,name=slug,proto3,oneof"`
}

func (*GetOrganizationRequest_Id) isGetOrganizationRequest_Identifier() {}

func (*GetOrganizationRequest_Slug) isGetOrganizationRequest_Identifier() {}

type GetOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organization  *OrganizationInfo      `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrganizationResponse) Reset() {
	*x = GetOrganizationResponse{}
	mi := &file_authlayer_v1_organization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationResponse) ProtoMessage() {}

func (x *GetOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_organization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationResponse.ProtoReflect.Descriptor instead.
func (*GetOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_organization_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrganizationResponse) GetOrganization() *OrganizationInfo {
	if x != nil {
		return x.Organization
	}
	return nil
}

type UpdateOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Slug          *string                `protobuf:"bytes,3,opt,name=slug,proto3,oneof" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrganizationRequest) Reset() {
	*x = UpdateOrganizationRequest{}
	mi := &file_authlayer_v1_organization_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrganizationRequest) ProtoMessage() {}

func (x *UpdateOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_organization_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrganizationRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_organization_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateOrganizationRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetSlug() string {
	if x != nil && x.Slug != nil {
		return *x.Slug
	}
	return ""
}

type UpdateOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organization  *OrganizationInfo      `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrganizationResponse) Reset() {
	*x = UpdateOrganizationResponse{}
	mi := &file_authlayer_v1_organization_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrganizationResponse) ProtoMessage() {}

func (x *UpdateOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_organization_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrganizationResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_organization_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateOrganizationResponse) GetOrganization() *OrganizationInfo {
	if x != nil {
		return x.Organization
	}
	return nil
}

type DeleteOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrganizationRequest) Reset() {
	*x = DeleteOrganizationRequest{}
	mi := &file_authlayer_v1_organization_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrganizationRequest) ProtoMessage() {}

func (x *DeleteOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_organization_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrganizationRequest.ProtoReflect.Descriptor instead.
func (*DeleteOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_organization_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteOrganizationRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type DeleteOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrganizationResponse) Reset() {
	*x = DeleteOrganizationResponse{}
	mi := &file_authlayer_v1_organization_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrganizationResponse) ProtoMessage() {}

func (x *DeleteOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_organization_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrganizationResponse.ProtoReflect.Descriptor instead.
func (*DeleteOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_organization_proto_rawDescGZIP(), []int{8}
}

type ListOrganizationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PaginationRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrganizationsRequest) Reset() {
	*x = ListOrganizationsRequest{}
	mi := &file_authlayer_v1_organization_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationsRequest) ProtoMessage() {}

func (x *ListOrganizationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_organization_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationsRequest.ProtoReflect.Descriptor instead.
func (*ListOrganizationsRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_organization_proto_rawDescGZIP(), []int{9}
}

func (x *ListOrganizationsRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListOrganizationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organizations []*OrganizationInfo    `protobuf:"bytes,1,rep,name=organizations,proto3" json:"organizations,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrganizationsResponse) Reset() {
	*x = ListOrganizationsResponse{}
	mi := &file_authlayer_v1_organization_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationsResponse) ProtoMessage() {}

func (x *ListOrganizationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_organization_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationsResponse.ProtoReflect.Descriptor instead.
func (*ListOrganizationsResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_organization_proto_rawDescGZIP(), []int{10}
}

func (x *ListOrganizationsResponse) GetOrganizations() []*OrganizationInfo {
	if x != nil {
		return x.Organizations
	}
	return nil
}

func (x *ListOrganizationsResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListOrgMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Pagination    *PaginationRequest     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrgMembersRequest) Reset() {
	*x = ListOrgMembersRequest{}
	mi := &file_authlayer_v1_organization_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrgMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrgMembersRequest) ProtoMessage() {}

func (x *ListOrgMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_organization_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrgMembersRequest.ProtoReflect.Descriptor instead.
func (*ListOrgMembersRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_organization_proto_rawDescGZIP(), []int{11}
}

func (x *ListOrgMembersRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ListOrgMembersRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListOrgMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*MemberInfo          `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrgMembersResponse) Reset() {
	*x = ListOrgMembersResponse{}
	mi := &file_authlayer_v1_organization_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrgMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrgMembersResponse) ProtoMessage() {}

func (x *ListOrgMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_organization_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrgMembersResponse.ProtoReflect.Descriptor instead.
func (*ListOrgMembersResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_organization_proto_rawDescGZIP(), []int{12}
}

func (x *ListOrgMembersResponse) GetMembers() []*MemberInfo {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *ListOrgMembersResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type InviteMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	RoleId        string                 `protobuf:"bytes,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteMemberRequest) Reset() {
	*x = InviteMemberRequest{}
	mi := &file_authlayer_v1_organization_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteMemberRequest) ProtoMessage() {}

func (x *InviteMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_organization_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteMemberRequest.ProtoReflect.Descriptor instead.
func (*InviteMemberRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_organization_proto_rawDescGZIP(), []int{13}
}

func (x *InviteMemberRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *InviteMemberRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *InviteMemberRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

type InviteMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvitationId  string                 `protobuf:"bytes,1,opt,name=invitation_id,json=invitationId,proto3" json:"invitation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteMemberResponse) Reset() {
	*x = InviteMemberResponse{}
	mi := &file_authlayer_v1_organization_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteMemberResponse) ProtoMessage() {}

func (x *InviteMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_organization_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteMemberResponse.ProtoReflect.Descriptor instead.
func (*InviteMemberResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_organization_proto_rawDescGZIP(), []int{14}
}

func (x *InviteMemberResponse) GetInvitationId() string {
	if x != nil {
		return x.InvitationId
	}
	return ""
}

type AcceptInvitationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptInvitationRequest) Reset() {
	*x = AcceptInvitationRequest{}
	mi := &file_authlayer_v1_organization_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptInvitationRequest) ProtoMessage() {}

func (x *AcceptInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_organization_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptInvitationRequest.ProtoReflect.Descriptor instead.
func (*AcceptInvitationRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_organization_proto_rawDescGZIP(), []int{15}
}

func (x *AcceptInvitationRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AcceptInvitationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organization  *OrganizationInfo      `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptInvitationResponse) Reset() {
	*x = AcceptInvitationResponse{}
	mi := &file_authlayer_v1_organization_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptInvitationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptInvitationResponse) ProtoMessage() {}

func (x *AcceptInvitationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_organization_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptInvitationResponse.ProtoReflect.Descriptor instead.
func (*AcceptInvitationResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_organization_proto_rawDescGZIP(), []int{16}
}

func (x *AcceptInvitationResponse) GetOrganization() *OrganizationInfo {
	if x != nil {
		return x.Organization
	}
	return nil
}

type RemoveOrgMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveOrgMemberRequest) Reset() {
	*x = RemoveOrgMemberRequest{}
	mi := &file_authlayer_v1_organization_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveOrgMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveOrgMemberRequest) ProtoMessage() {}

func (x *RemoveOrgMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_organization_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveOrgMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveOrgMemberRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_organization_proto_rawDescGZIP(), []int{17}
}

func (x *RemoveOrgMemberRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *RemoveOrgMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RemoveOrgMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveOrgMemberResponse) Reset() {
	*x = RemoveOrgMemberResponse{}
	mi := &file_authlayer_v1_organization_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveOrgMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveOrgMemberResponse) ProtoMessage() {}

func (x *RemoveOrgMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_organization_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveOrgMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveOrgMemberResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_organization_proto_rawDescGZIP(), []int{18}
}

type UpdateOrgMemberRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId        string                 `protobuf:"bytes,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrgMemberRoleRequest) Reset() {
	*x = UpdateOrgMemberRoleRequest{}
	mi := &file_authlayer_v1_organization_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrgMemberRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrgMemberRoleRequest) ProtoMessage() {}

func (x *UpdateOrgMemberRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_organization_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrgMemberRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrgMemberRoleRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_organization_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateOrgMemberRoleRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *UpdateOrgMemberRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateOrgMemberRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

type UpdateOrgMemberRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrgMemberRoleResponse) Reset() {
	*x = UpdateOrgMemberRoleResponse{}
	mi := &file_authlayer_v1_organization_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrgMemberRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrgMemberRoleResponse) ProtoMessage() {}

func (x *UpdateOrgMemberRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_organization_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrgMemberRoleResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrgMemberRoleResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_organization_proto_rawDescGZIP(), []int{20}
}

var File_authlayer_v1_organization_proto protoreflect.FileDescriptor

const file_authlayer_v1_organization_proto_rawDesc = "" +
	"\n" +
	"\x1fauthlayer/v1/organization.proto\x12\fauthlayer.v1\x1a\x19authlayer/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa0\x01\n" +
	"\x10OrganizationInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\tR\aownerId\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"C\n" +
	"\x19CreateOrganizationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\"`\n" +
	"\x1aCreateOrganizationResponse\x12B\n" +
	"\forganization\x18\x01 \x01(\v2\x1e.authlayer.v1.OrganizationInfoR\forganization\"N\n" +
	"\x16GetOrganizationRequest\x12\x10\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x12\x14\n" +
	"\x04slug\x18\x02 \x01(\tH\x00R\x04slugB\f\n" +
	"\n" +
	"identifier\"]\n" +
	"\x17GetOrganizationResponse\x12B\n" +
	"\forganization\x18\x01 \x01(\v2\x1e.authlayer.v1.OrganizationInfoR\forganization\"v\n" +
	"\x19UpdateOrganizationRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x17\n" +
	"\x04slug\x18\x03 \x01(\tH\x01R\x04slug\x88\x01\x01B\a\n" +
	"\x05_nameB\a\n" +
	"\x05_slug\"`\n" +
	"\x1aUpdateOrganizationResponse\x12B\n" +
	"\forganization\x18\x01 \x01(\v2\x1e.authlayer.v1.OrganizationInfoR\forganization\"2\n" +
	"\x19DeleteOrganizationRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\"\x1c\n" +
	"\x1aDeleteOrganizationResponse\"[\n" +
	"\x18ListOrganizationsRequest\x12?\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1f.authlayer.v1.PaginationRequestR\n" +
	"pagination\"\xa3\x01\n" +
	"\x19ListOrganizationsResponse\x12D\n" +
	"\rorganizations\x18\x01 \x03(\v2\x1e.authlayer.v1.OrganizationInfoR\rorganizations\x12@\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2 .authlayer.v1.PaginationResponseR\n" +
	"pagination\"o\n" +
	"\x15ListOrgMembersRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12?\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1f.authlayer.v1.PaginationRequestR\n" +
	"pagination\"\x8e\x01\n" +
	"\x16ListOrgMembersResponse\x122\n" +
	"\amembers\x18\x01 \x03(\v2\x18.authlayer.v1.MemberInfoR\amembers\x12@\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2 .authlayer.v1.PaginationResponseR\n" +
	"pagination\"[\n" +
	"\x13InviteMemberRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\tR\x06roleId\";\n" +
	"\x14InviteMemberResponse\x12#\n" +
	"\rinvitation_id\x18\x01 \x01(\tR\finvitationId\"/\n" +
	"\x17AcceptInvitationRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"^\n" +
	"\x18AcceptInvitationResponse\x12B\n" +
	"\forganization\x18\x01 \x01(\v2\x1e.authlayer.v1.OrganizationInfoR\forganization\"H\n" +
	"\x16RemoveOrgMemberRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x19\n" +
	"\x17RemoveOrgMemberResponse\"e\n" +
	"\x1aUpdateOrgMemberRoleRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\tR\x06roleId\"\x1d\n" +
	"\x1bUpdateOrgMemberRoleResponse2\xf0\a\n" +
	"\x13OrganizationService\x12g\n" +
	"\x12CreateOrganization\x12'.authlayer.v1.CreateOrganizationRequest\x1a(.authlayer.v1.CreateOrganizationResponse\x12^\n" +
	"\x0fGetOrganization\x12$.authlayer.v1.GetOrganizationRequest\x1a%.authlayer.v1.GetOrganizationResponse\x12g\n" +
	"\x12UpdateOrganization\x12'.authlayer.v1.UpdateOrganizationRequest\x1a(.authlayer.v1.UpdateOrganizationResponse\x12g\n" +
	"\x12DeleteOrganization\x12'.authlayer.v1.DeleteOrganizationRequest\x1a(.authlayer.v1.DeleteOrganizationResponse\x12d\n" +
	"\x11ListOrganizations\x12&.authlayer.v1.ListOrganizationsRequest\x1a'.authlayer.v1.ListOrganizationsResponse\x12X\n" +
	"\vListMembers\x12#.authlayer.v1.ListOrgMembersRequest\x1a$.authlayer.v1.ListOrgMembersResponse\x12U\n" +
	"\fInviteMember\x12!.authlayer.v1.InviteMemberRequest\x1a\".authlayer.v1.InviteMemberResponse\x12a\n" +
	"\x10AcceptInvitation\x12%.authlayer.v1.AcceptInvitationRequest\x1a&.authlayer.v1.AcceptInvitationResponse\x12[\n" +
	"\fRemoveMember\x12$.authlayer.v1.RemoveOrgMemberRequest\x1a%.authlayer.v1.RemoveOrgMemberResponse\x12g\n" +
	"\x10UpdateMemberRole\x12(.authlayer.v1.UpdateOrgMemberRoleRequest\x1a).authlayer.v1.UpdateOrgMemberRoleResponseBJZHgithub.com/bernardoforcillo/authlayer/pkg/proto/authlayer/v1;authlayerv1b\x06proto3"

var (
	file_authlayer_v1_organization_proto_rawDescOnce sync.Once
	file_authlayer_v1_organization_proto_rawDescData []byte
)

func file_authlayer_v1_organization_proto_rawDescGZIP() []byte {
	file_authlayer_v1_organization_proto_rawDescOnce.Do(func() {
		file_authlayer_v1_organization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authlayer_v1_organization_proto_rawDesc), len(file_authlayer_v1_organization_proto_rawDesc)))
	})
	return file_authlayer_v1_organization_proto_rawDescData
}

var file_authlayer_v1_organization_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_authlayer_v1_organization_proto_goTypes = []any{
	(*OrganizationInfo)(nil),            // 0: authlayer.v1.OrganizationInfo
	(*CreateOrganizationRequest)(nil),   // 1: authlayer.v1.CreateOrganizationRequest
	(*CreateOrganizationResponse)(nil),  // 2: authlayer.v1.CreateOrganizationResponse
	(*GetOrganizationRequest)(nil),      // 3: authlayer.v1.GetOrganizationRequest
	(*GetOrganizationResponse)(nil),     // 4: authlayer.v1.GetOrganizationResponse
	(*UpdateOrganizationRequest)(nil),   // 5: authlayer.v1.UpdateOrganizationRequest
	(*UpdateOrganizationResponse)(nil),  // 6: authlayer.v1.UpdateOrganizationResponse
	(*DeleteOrganizationRequest)(nil),   // 7: authlayer.v1.DeleteOrganizationRequest
	(*DeleteOrganizationResponse)(nil),  // 8: authlayer.v1.DeleteOrganizationResponse
	(*ListOrganizationsRequest)(nil),    // 9: authlayer.v1.ListOrganizationsRequest
	(*ListOrganizationsResponse)(nil),   // 10: authlayer.v1.ListOrganizationsResponse
	(*ListOrgMembersRequest)(nil),       // 11: authlayer.v1.ListOrgMembersRequest
	(*ListOrgMembersResponse)(nil),      // 12: authlayer.v1.ListOrgMembersResponse
	(*InviteMemberRequest)(nil),         // 13: authlayer.v1.InviteMemberRequest
	(*InviteMemberResponse)(nil),        // 14: authlayer.v1.InviteMemberResponse
	(*AcceptInvitationRequest)(nil),     // 15: authlayer.v1.AcceptInvitationRequest
	(*AcceptInvitationResponse)(nil),    // 16: authlayer.v1.AcceptInvitationResponse
	(*RemoveOrgMemberRequest)(nil),      // 17: authlayer.v1.RemoveOrgMemberRequest
	(*RemoveOrgMemberResponse)(nil),     // 18: authlayer.v1.RemoveOrgMemberResponse
	(*UpdateOrgMemberRoleRequest)(nil),  // 19: authlayer.v1.UpdateOrgMemberRoleRequest
	(*UpdateOrgMemberRoleResponse)(nil), // 20: authlayer.v1.UpdateOrgMemberRoleResponse
	(*timestamppb.Timestamp)(nil),       // 21: google.protobuf.Timestamp
	(*PaginationRequest)(nil),           // 22: authlayer.v1.PaginationRequest
	(*PaginationResponse)(nil),          // 23: authlayer.v1.PaginationResponse
	(*MemberInfo)(nil),                  // 24: authlayer.v1.MemberInfo
}
var file_authlayer_v1_organization_proto_depIdxs = []int32{
	21, // 0: authlayer.v1.OrganizationInfo.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: authlayer.v1.CreateOrganizationResponse.organization:type_name -> authlayer.v1.OrganizationInfo
	0,  // 2: authlayer.v1.GetOrganizationResponse.organization:type_name -> authlayer.v1.OrganizationInfo
	0,  // 3: authlayer.v1.UpdateOrganizationResponse.organization:type_name -> authlayer.v1.OrganizationInfo
	22, // 4: authlayer.v1.ListOrganizationsRequest.pagination:type_name -> authlayer.v1.PaginationRequest
	0,  // 5: authlayer.v1.ListOrganizationsResponse.organizations:type_name -> authlayer.v1.OrganizationInfo
	23, // 6: authlayer.v1.ListOrganizationsResponse.pagination:type_name -> authlayer.v1.PaginationResponse
	22, // 7: authlayer.v1.ListOrgMembersRequest.pagination:type_name -> authlayer.v1.PaginationRequest
	24, // 8: authlayer.v1.ListOrgMembersResponse.members:type_name -> authlayer.v1.MemberInfo
	23, // 9: authlayer.v1.ListOrgMembersResponse.pagination:type_name -> authlayer.v1.PaginationResponse
	0,  // 10: authlayer.v1.AcceptInvitationResponse.organization:type_name -> authlayer.v1.OrganizationInfo
	1,  // 11: authlayer.v1.OrganizationService.CreateOrganization:input_type -> authlayer.v1.CreateOrganizationRequest
	3,  // 12: authlayer.v1.OrganizationService.GetOrganization:input_type -> authlayer.v1.GetOrganizationRequest
	5,  // 13: authlayer.v1.OrganizationService.UpdateOrganization:input_type -> authlayer.v1.UpdateOrganizationRequest
	7,  // 14: authlayer.v1.OrganizationService.DeleteOrganization:input_type -> authlayer.v1.DeleteOrganizationRequest
	9,  // 15: authlayer.v1.OrganizationService.ListOrganizations:input_type -> authlayer.v1.ListOrganizationsRequest
	11, // 16: authlayer.v1.OrganizationService.ListMembers:input_type -> authlayer.v1.ListOrgMembersRequest
	13, // 17: authlayer.v1.OrganizationService.InviteMember:input_type -> authlayer.v1.InviteMemberRequest
	15, // 18: authlayer.v1.OrganizationService.AcceptInvitation:input_type -> authlayer.v1.AcceptInvitationRequest
	17, // 19: authlayer.v1.OrganizationService.RemoveMember:input_type -> authlayer.v1.RemoveOrgMemberRequest
	19, // 20: authlayer.v1.OrganizationService.UpdateMemberRole:input_type -> authlayer.v1.UpdateOrgMemberRoleRequest
	2,  // 21: authlayer.v1.OrganizationService.CreateOrganization:output_type -> authlayer.v1.CreateOrganizationResponse
	4,  // 22: authlayer.v1.OrganizationService.GetOrganization:output_type -> authlayer.v1.GetOrganizationResponse
	6,  // 23: authlayer.v1.OrganizationService.UpdateOrganization:output_type -> authlayer.v1.UpdateOrganizationResponse
	8,  // 24: authlayer.v1.OrganizationService.DeleteOrganization:output_type -> authlayer.v1.DeleteOrganizationResponse
	10, // 25: authlayer.v1.OrganizationService.ListOrganizations:output_type -> authlayer.v1.ListOrganizationsResponse
	12, // 26: authlayer.v1.OrganizationService.ListMembers:output_type -> authlayer.v1.ListOrgMembersResponse
	14, // 27: authlayer.v1.OrganizationService.InviteMember:output_type -> authlayer.v1.InviteMemberResponse
	16, // 28: authlayer.v1.OrganizationService.AcceptInvitation:output_type -> authlayer.v1.AcceptInvitationResponse
	18, // 29: authlayer.v1.OrganizationService.RemoveMember:output_type -> authlayer.v1.RemoveOrgMemberResponse
	20, // 30: authlayer.v1.OrganizationService.UpdateMemberRole:output_type -> authlayer.v1.UpdateOrgMemberRoleResponse
	21, // [21:31] is the sub-list for method output_type
	11, // [11:21] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_authlayer_v1_organization_proto_init() }
func file_authlayer_v1_organization_proto_init() {
	if File_authlayer_v1_organization_proto != nil {
		return
	}
	file_authlayer_v1_common_proto_init()
	file_authlayer_v1_organization_proto_msgTypes[3].OneofWrappers = []any{
		(*GetOrganizationRequest_Id)(nil),
		(*GetOrganizationRequest_Slug)(nil),
	}
	file_authlayer_v1_organization_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authlayer_v1_organization_proto_rawDesc), len(file_authlayer_v1_organization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authlayer_v1_organization_proto_goTypes,
		DependencyIndexes: file_authlayer_v1_organization_proto_depIdxs,
		MessageInfos:      file_authlayer_v1_organization_proto_msgTypes,
	}.Build()
	File_authlayer_v1_organization_proto = out.File
	file_authlayer_v1_organization_proto_goTypes = nil
	file_authlayer_v1_organization_proto_depIdxs = nil
}
