// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: authlayer/v1/rbac.proto

package authlayerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	OrgId         *string                `protobuf:"bytes,4,opt,name=org_id,json=orgId,proto3,oneof" json:"org_id,omitempty"`
	ParentRoleId  *string                `protobuf:"bytes,5,opt,name=parent_role_id,json=parentRoleId,proto3,oneof" json:"parent_role_id,omitempty"`
	Permissions   []*PermissionInfo      `protobuf:"bytes,6,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleInfo) Reset() {
	*x = RoleInfo{}
	mi := &file_authlayer_v1_rbac_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleInfo) ProtoMessage() {}

func (x *RoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_rbac_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleInfo.ProtoReflect.Descriptor instead.
func (*RoleInfo) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_rbac_proto_rawDescGZIP(), []int{0}
}

func (x *RoleInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoleInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleInfo) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *RoleInfo) GetOrgId() string {
	if x != nil && x.OrgId != nil {
		return *x.OrgId
	}
	return ""
}

func (x *RoleInfo) GetParentRoleId() string {
	if x != nil && x.ParentRoleId != nil {
		return *x.ParentRoleId
	}
	return ""
}

func (x *RoleInfo) GetPermissions() []*PermissionInfo {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type PermissionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionInfo) Reset() {
	*x = PermissionInfo{}
	mi := &file_authlayer_v1_rbac_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionInfo) ProtoMessage() {}

func (x *PermissionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_rbac_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionInfo.ProtoReflect.Descriptor instead.
func (*PermissionInfo) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_rbac_proto_rawDescGZIP(), []int{1}
}

func (x *PermissionInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PermissionInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PermissionInfo) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	OrgId         *string                `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3,oneof" json:"org_id,omitempty"`
	ParentRoleId  *string                `protobuf:"bytes,4,opt,name=parent_role_id,json=parentRoleId,proto3,oneof" json:"parent_role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_authlayer_v1_rbac_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_rbac_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_rbac_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateRoleRequest) GetOrgId() string {
	if x != nil && x.OrgId != nil {
		return *x.OrgId
	}
	return ""
}

func (x *CreateRoleRequest) GetParentRoleId() string {
	if x != nil && x.ParentRoleId != nil {
		return *x.ParentRoleId
	}
	return ""
}

type CreateRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *RoleInfo              `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleResponse) Reset() {
	*x = CreateRoleResponse{}
	mi := &file_authlayer_v1_rbac_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleResponse) ProtoMessage() {}

func (x *CreateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_rbac_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleResponse.ProtoReflect.Descriptor instead.
func (*CreateRoleResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_rbac_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRoleResponse) GetRole() *RoleInfo {
	if x != nil {
		return x.Role
	}
	return nil
}

type GetRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        string                 `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleRequest) Reset() {
	*x = GetRoleRequest{}
	mi := &file_authlayer_v1_rbac_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleRequest) ProtoMessage() {}

func (x *GetRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_rbac_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleRequest.ProtoReflect.Descriptor instead.
func (*GetRoleRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_rbac_proto_rawDescGZIP(), []int{4}
}

func (x *GetRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

type GetRoleResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Role                 *RoleInfo              `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	InheritedPermissions []*PermissionInfo      `protobuf:"bytes,2,rep,name=inherited_permissions,json=inheritedPermissions,proto3" json:"inherited_permissions,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetRoleResponse) Reset() {
	*x = GetRoleResponse{}
	mi := &file_authlayer_v1_rbac_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleResponse) ProtoMessage() {}

func (x *GetRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_rbac_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleResponse.ProtoReflect.Descriptor instead.
func (*GetRoleResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_rbac_proto_rawDescGZIP(), []int{5}
}

func (x *GetRoleResponse) GetRole() *RoleInfo {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *GetRoleResponse) GetInheritedPermissions() []*PermissionInfo {
	if x != nil {
		return x.InheritedPermissions
	}
	return nil
}

type UpdateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        string                 `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	ParentRoleId  *string                `protobuf:"bytes,4,opt,name=parent_role_id,json=parentRoleId,proto3,oneof" json:"parent_role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_authlayer_v1_rbac_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_rbac_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_rbac_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *UpdateRoleRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateRoleRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateRoleRequest) GetParentRoleId() string {
	if x != nil && x.ParentRoleId != nil {
		return *x.ParentRoleId
	}
	return ""
}

type UpdateRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *RoleInfo              `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleResponse) Reset() {
	*x = UpdateRoleResponse{}
	mi := &file_authlayer_v1_rbac_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleResponse) ProtoMessage() {}

func (x *UpdateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_rbac_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoleResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_rbac_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateRoleResponse) GetRole() *RoleInfo {
	if x != nil {
		return x.Role
	}
	return nil
}

type DeleteRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        string                 `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRequest) Reset() {
	*x = DeleteRoleRequest{}
	mi := &file_authlayer_v1_rbac_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequest) ProtoMessage() {}

func (x *DeleteRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_rbac_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_rbac_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

type DeleteRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleResponse) Reset() {
	*x = DeleteRoleResponse{}
	mi := &file_authlayer_v1_rbac_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleResponse) ProtoMessage() {}

func (x *DeleteRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_rbac_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleResponse.ProtoReflect.Descriptor instead.
func (*DeleteRoleResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_rbac_proto_rawDescGZIP(), []int{9}
}

type ListRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         *string                `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3,oneof" json:"org_id,omitempty"`
	Pagination    *PaginationRequest     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesRequest) Reset() {
	*x = ListRolesRequest{}
	mi := &file_authlayer_v1_rbac_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesRequest) ProtoMessage() {}

func (x *ListRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_rbac_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesRequest.ProtoReflect.Descriptor instead.
func (*ListRolesRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_rbac_proto_rawDescGZIP(), []int{10}
}

func (x *ListRolesRequest) GetOrgId() string {
	if x != nil && x.OrgId != nil {
		return *x.OrgId
	}
	return ""
}

func (x *ListRolesRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*RoleInfo            `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesResponse) Reset() {
	*x = ListRolesResponse{}
	mi := &file_authlayer_v1_rbac_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesResponse) ProtoMessage() {}

func (x *ListRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_rbac_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesResponse.ProtoReflect.Descriptor instead.
func (*ListRolesResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_rbac_proto_rawDescGZIP(), []int{11}
}

func (x *ListRolesResponse) GetRoles() []*RoleInfo {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ListRolesResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type AssignRoleRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId string                 `protobuf:"bytes,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	// Types that are valid to be assigned to Scope:
	//
	//	*AssignRoleRequest_OrgId
	//	*AssignRoleRequest_TeamId
	Scope         isAssignRoleRequest_Scope `protobuf_oneof:"scope"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleRequest) Reset() {
	*x = AssignRoleRequest{}
	mi := &file_authlayer_v1_rbac_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleRequest) ProtoMessage() {}

func (x *AssignRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_rbac_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleRequest.ProtoReflect.Descriptor instead.
func (*AssignRoleRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_rbac_proto_rawDescGZIP(), []int{12}
}

func (x *AssignRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssignRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *AssignRoleRequest) GetScope() isAssignRoleRequest_Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *AssignRoleRequest) GetOrgId() string {
	if x != nil {
		if x, ok := x.Scope.(*AssignRoleRequest_OrgId); ok {
			return x.OrgId
		}
	}
	return ""
}

func (x *AssignRoleRequest) GetTeamId() string {
	if x != nil {
		if x, ok := x.Scope.(*AssignRoleRequest_TeamId); ok {
			return x.TeamId
		}
	}
	return ""
}

type isAssignRoleRequest_Scope interface {
	isAssignRoleRequest_Scope()
}

type AssignRoleRequest_OrgId struct {
	OrgId string `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3,oneof"`
}

type AssignRoleRequest_TeamId struct {
	TeamId string `protobuf:"bytes,4,opt,name=team_id,json=teamId,proto3,oneof"`
}

func (*AssignRoleRequest_OrgId) isAssignRoleRequest_Scope() {}

func (*AssignRoleRequest_TeamId) isAssignRoleRequest_Scope() {}

type AssignRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleResponse) Reset() {
	*x = AssignRoleResponse{}
	mi := &file_authlayer_v1_rbac_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleResponse) ProtoMessage() {}

func (x *AssignRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_rbac_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleResponse.ProtoReflect.Descriptor instead.
func (*AssignRoleResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_rbac_proto_rawDescGZIP(), []int{13}
}

type RevokeRoleRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId string                 `protobuf:"bytes,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	// Types that are valid to be assigned to Scope:
	//
	//	*RevokeRoleRequest_OrgId
	//	*RevokeRoleRequest_TeamId
	Scope         isRevokeRoleRequest_Scope `protobuf_oneof:"scope"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRoleRequest) Reset() {
	*x = RevokeRoleRequest{}
	mi := &file_authlayer_v1_rbac_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRoleRequest) ProtoMessage() {}

func (x *RevokeRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_rbac_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRoleRequest.ProtoReflect.Descriptor instead.
func (*RevokeRoleRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_rbac_proto_rawDescGZIP(), []int{14}
}

func (x *RevokeRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RevokeRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *RevokeRoleRequest) GetScope() isRevokeRoleRequest_Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *RevokeRoleRequest) GetOrgId() string {
	if x != nil {
		if x, ok := x.Scope.(*RevokeRoleRequest_OrgId); ok {
			return x.OrgId
		}
	}
	return ""
}

func (x *RevokeRoleRequest) GetTeamId() string {
	if x != nil {
		if x, ok := x.Scope.(*RevokeRoleRequest_TeamId); ok {
			return x.TeamId
		}
	}
	return ""
}

type isRevokeRoleRequest_Scope interface {
	isRevokeRoleRequest_Scope()
}

type RevokeRoleRequest_OrgId struct {
	OrgId string `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3,oneof"`
}

type RevokeRoleRequest_TeamId struct {
	TeamId string `protobuf:"bytes,4,opt,name=team_id,json=teamId,proto3,oneof"`
}

func (*RevokeRoleRequest_OrgId) isRevokeRoleRequest_Scope() {}

func (*RevokeRoleRequest_TeamId) isRevokeRoleRequest_Scope() {}

type RevokeRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRoleResponse) Reset() {
	*x = RevokeRoleResponse{}
	mi := &file_authlayer_v1_rbac_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRoleResponse) ProtoMessage() {}

func (x *RevokeRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_rbac_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRoleResponse.ProtoReflect.Descriptor instead.
func (*RevokeRoleResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_rbac_proto_rawDescGZIP(), []int{15}
}

type CreatePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionRequest) Reset() {
	*x = CreatePermissionRequest{}
	mi := &file_authlayer_v1_rbac_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionRequest) ProtoMessage() {}

func (x *CreatePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_rbac_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionRequest.ProtoReflect.Descriptor instead.
func (*CreatePermissionRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_rbac_proto_rawDescGZIP(), []int{16}
}

func (x *CreatePermissionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePermissionRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type CreatePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permission    *PermissionInfo        `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionResponse) Reset() {
	*x = CreatePermissionResponse{}
	mi := &file_authlayer_v1_rbac_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionResponse) ProtoMessage() {}

func (x *CreatePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_rbac_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionResponse.ProtoReflect.Descriptor instead.
func (*CreatePermissionResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_rbac_proto_rawDescGZIP(), []int{17}
}

func (x *CreatePermissionResponse) GetPermission() *PermissionInfo {
	if x != nil {
		return x.Permission
	}
	return nil
}

type ListPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PaginationRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsRequest) Reset() {
	*x = ListPermissionsRequest{}
	mi := &file_authlayer_v1_rbac_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsRequest) ProtoMessage() {}

func (x *ListPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_rbac_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsRequest.ProtoReflect.Descriptor instead.
func (*ListPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_rbac_proto_rawDescGZIP(), []int{18}
}

func (x *ListPermissionsRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []*PermissionInfo      `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsResponse) Reset() {
	*x = ListPermissionsResponse{}
	mi := &file_authlayer_v1_rbac_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsResponse) ProtoMessage() {}

func (x *ListPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_rbac_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsResponse.ProtoReflect.Descriptor instead.
func (*ListPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_rbac_proto_rawDescGZIP(), []int{19}
}

func (x *ListPermissionsResponse) GetPermissions() []*PermissionInfo {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *ListPermissionsResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type AssignPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        string                 `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	PermissionId  string                 `protobuf:"bytes,2,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignPermissionRequest) Reset() {
	*x = AssignPermissionRequest{}
	mi := &file_authlayer_v1_rbac_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignPermissionRequest) ProtoMessage() {}

func (x *AssignPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_rbac_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignPermissionRequest.ProtoReflect.Descriptor instead.
func (*AssignPermissionRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_rbac_proto_rawDescGZIP(), []int{20}
}

func (x *AssignPermissionRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *AssignPermissionRequest) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

type AssignPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignPermissionResponse) Reset() {
	*x = AssignPermissionResponse{}
	mi := &file_authlayer_v1_rbac_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignPermissionResponse) ProtoMessage() {}

func (x *AssignPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_rbac_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignPermissionResponse.ProtoReflect.Descriptor instead.
func (*AssignPermissionResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_rbac_proto_rawDescGZIP(), []int{21}
}

type RevokePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        string                 `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	PermissionId  string                 `protobuf:"bytes,2,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokePermissionRequest) Reset() {
	*x = RevokePermissionRequest{}
	mi := &file_authlayer_v1_rbac_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokePermissionRequest) ProtoMessage() {}

func (x *RevokePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_rbac_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokePermissionRequest.ProtoReflect.Descriptor instead.
func (*RevokePermissionRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_rbac_proto_rawDescGZIP(), []int{22}
}

func (x *RevokePermissionRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *RevokePermissionRequest) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

type RevokePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokePermissionResponse) Reset() {
	*x = RevokePermissionResponse{}
	mi := &file_authlayer_v1_rbac_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokePermissionResponse) ProtoMessage() {}

func (x *RevokePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_rbac_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokePermissionResponse.ProtoReflect.Descriptor instead.
func (*RevokePermissionResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_rbac_proto_rawDescGZIP(), []int{23}
}

type CheckPermissionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PermissionName string                 `protobuf:"bytes,2,opt,name=permission_name,json=permissionName,proto3" json:"permission_name,omitempty"`
	OrgId          *string                `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3,oneof" json:"org_id,omitempty"`
	TeamId         *string                `protobuf:"bytes,4,opt,name=team_id,json=teamId,proto3,oneof" json:"team_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckPermissionRequest) Reset() {
	*x = CheckPermissionRequest{}
	mi := &file_authlayer_v1_rbac_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionRequest) ProtoMessage() {}

func (x *CheckPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_rbac_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionRequest.ProtoReflect.Descriptor instead.
func (*CheckPermissionRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_rbac_proto_rawDescGZIP(), []int{24}
}

func (x *CheckPermissionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckPermissionRequest) GetPermissionName() string {
	if x != nil {
		return x.PermissionName
	}
	return ""
}

func (x *CheckPermissionRequest) GetOrgId() string {
	if x != nil && x.OrgId != nil {
		return *x.OrgId
	}
	return ""
}

func (x *CheckPermissionRequest) GetTeamId() string {
	if x != nil && x.TeamId != nil {
		return *x.TeamId
	}
	return ""
}

type CheckPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	MatchedRole   string                 `protobuf:"bytes,2,opt,name=matched_role,json=matchedRole,proto3" json:"matched_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionResponse) Reset() {
	*x = CheckPermissionResponse{}
	mi := &file_authlayer_v1_rbac_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionResponse) ProtoMessage() {}

func (x *CheckPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_rbac_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionResponse.ProtoReflect.Descriptor instead.
func (*CheckPermissionResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_rbac_proto_rawDescGZIP(), []int{25}
}

func (x *CheckPermissionResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckPermissionResponse) GetMatchedRole() string {
	if x != nil {
		return x.MatchedRole
	}
	return ""
}

type GetUserPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrgId         *string                `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3,oneof" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPermissionsRequest) Reset() {
	*x = GetUserPermissionsRequest{}
	mi := &file_authlayer_v1_rbac_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPermissionsRequest) ProtoMessage() {}

func (x *GetUserPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_rbac_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPermissionsRequest.ProtoReflect.Descriptor instead.
func (*GetUserPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_rbac_proto_rawDescGZIP(), []int{26}
}

func (x *GetUserPermissionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserPermissionsRequest) GetOrgId() string {
	if x != nil && x.OrgId != nil {
		return *x.OrgId
	}
	return ""
}

type GetUserPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []*PermissionInfo      `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPermissionsResponse) Reset() {
	*x = GetUserPermissionsResponse{}
	mi := &file_authlayer_v1_rbac_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPermissionsResponse) ProtoMessage() {}

func (x *GetUserPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_rbac_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPermissionsResponse.ProtoReflect.Descriptor instead.
func (*GetUserPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_rbac_proto_rawDescGZIP(), []int{27}
}

func (x *GetUserPermissionsResponse) GetPermissions() []*PermissionInfo {
	if x != nil {
		return x.Permissions
	}
	return nil
}

var File_authlayer_v1_rbac_proto protoreflect.FileDescriptor

const file_authlayer_v1_rbac_proto_rawDesc = "" +
	"\n" +
	"\x17authlayer/v1/rbac.proto\x12\fauthlayer.v1\x1a\x19authlayer/v1/common.proto\"\x8a\x02\n" +
	"\bRoleInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1a\n" +
	"\x06org_id\x18\x04 \x01(\tH\x01R\x05orgId\x88\x01\x01\x12)\n" +
	"\x0eparent_role_id\x18\x05 \x01(\tH\x02R\fparentRoleId\x88\x01\x01\x12>\n" +
	"\vpermissions\x18\x06 \x03(\v2\x1c.authlayer.v1.PermissionInfoR\vpermissionsB\x0e\n" +
	"\f_descriptionB\t\n" +
	"\a_org_idB\x11\n" +
	"\x0f_parent_role_id\"k\n" +
	"\x0ePermissionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description\"\xc3\x01\n" +
	"\x11CreateRoleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1a\n" +
	"\x06org_id\x18\x03 \x01(\tH\x01R\x05orgId\x88\x01\x01\x12)\n" +
	"\x0eparent_role_id\x18\x04 \x01(\tH\x02R\fparentRoleId\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\t\n" +
	"\a_org_idB\x11\n" +
	"\x0f_parent_role_id\"@\n" +
	"\x12CreateRoleResponse\x12*\n" +
	"\x04role\x18\x01 \x01(\v2\x16.authlayer.v1.RoleInfoR\x04role\")\n" +
	"\x0eGetRoleRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\"\x90\x01\n" +
	"\x0fGetRoleResponse\x12*\n" +
	"\x04role\x18\x01 \x01(\v2\x16.authlayer.v1.RoleInfoR\x04role\x12Q\n" +
	"\x15inherited_permissions\x18\x02 \x03(\v2\x1c.authlayer.v1.PermissionInfoR\x14inheritedPermissions\"\xc3\x01\n" +
	"\x11UpdateRoleRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12)\n" +
	"\x0eparent_role_id\x18\x04 \x01(\tH\x02R\fparentRoleId\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\x11\n" +
	"\x0f_parent_role_id\"@\n" +
	"\x12UpdateRoleResponse\x12*\n" +
	"\x04role\x18\x01 \x01(\v2\x16.authlayer.v1.RoleInfoR\x04role\",\n" +
	"\x11DeleteRoleRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\"\x14\n" +
	"\x12DeleteRoleResponse\"z\n" +
	"\x10ListRolesRequest\x12\x1a\n" +
	"\x06org_id\x18\x01 \x01(\tH\x00R\x05orgId\x88\x01\x01\x12?\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1f.authlayer.v1.PaginationRequestR\n" +
	"paginationB\t\n" +
	"\a_org_id\"\x83\x01\n" +
	"\x11ListRolesResponse\x12,\n" +
	"\x05roles\x18\x01 \x03(\v2\x16.authlayer.v1.RoleInfoR\x05roles\x12@\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2 .authlayer.v1.PaginationResponseR\n" +
	"pagination\"\x82\x01\n" +
	"\x11AssignRoleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\tR\x06roleId\x12\x17\n" +
	"\x06org_id\x18\x03 \x01(\tH\x00R\x05orgId\x12\x19\n" +
	"\ateam_id\x18\x04 \x01(\tH\x00R\x06teamIdB\a\n" +
	"\x05scope\"\x14\n" +
	"\x12AssignRoleResponse\"\x82\x01\n" +
	"\x11RevokeRoleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\tR\x06roleId\x12\x17\n" +
	"\x06org_id\x18\x03 \x01(\tH\x00R\x05orgId\x12\x19\n" +
	"\ateam_id\x18\x04 \x01(\tH\x00R\x06teamIdB\a\n" +
	"\x05scope\"\x14\n" +
	"\x12RevokeRoleResponse\"d\n" +
	"\x17CreatePermissionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description\"X\n" +
	"\x18CreatePermissionResponse\x12<\n" +
	"\n" +
	"permission\x18\x01 \x01(\v2\x1c.authlayer.v1.PermissionInfoR\n" +
	"permission\"Y\n" +
	"\x16ListPermissionsRequest\x12?\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1f.authlayer.v1.PaginationRequestR\n" +
	"pagination\"\x9b\x01\n" +
	"\x17ListPermissionsResponse\x12>\n" +
	"\vpermissions\x18\x01 \x03(\v2\x1c.authlayer.v1.PermissionInfoR\vpermissions\x12@\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2 .authlayer.v1.PaginationResponseR\n" +
	"pagination\"W\n" +
	"\x17AssignPermissionRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\x12#\n" +
	"\rpermission_id\x18\x02 \x01(\tR\fpermissionId\"\x1a\n" +
	"\x18AssignPermissionResponse\"W\n" +
	"\x17RevokePermissionRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\x12#\n" +
	"\rpermission_id\x18\x02 \x01(\tR\fpermissionId\"\x1a\n" +
	"\x18RevokePermissionResponse\"\xab\x01\n" +
	"\x16CheckPermissionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fpermission_name\x18\x02 \x01(\tR\x0epermissionName\x12\x1a\n" +
	"\x06org_id\x18\x03 \x01(\tH\x00R\x05orgId\x88\x01\x01\x12\x1c\n" +
	"\ateam_id\x18\x04 \x01(\tH\x01R\x06teamId\x88\x01\x01B\t\n" +
	"\a_org_idB\n" +
	"\n" +
	"\b_team_id\"V\n" +
	"\x17CheckPermissionResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12!\n" +
	"\fmatched_role\x18\x02 \x01(\tR\vmatchedRole\"[\n" +
	"\x19GetUserPermissionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\x06org_id\x18\x02 \x01(\tH\x00R\x05orgId\x88\x01\x01B\t\n" +
	"\a_org_id\"\\\n" +
	"\x1aGetUserPermissionsResponse\x12>\n" +
	"\vpermissions\x18\x01 \x03(\v2\x1c.authlayer.v1.PermissionInfoR\vpermissions2\x8a\t\n" +
	"\vRBACService\x12O\n" +
	"\n" +
	"CreateRole\x12\x1f.authlayer.v1.CreateRoleRequest\x1a .authlayer.v1.CreateRoleResponse\x12F\n" +
	"\aGetRole\x12\x1c.authlayer.v1.GetRoleRequest\x1a\x1d.authlayer.v1.GetRoleResponse\x12O\n" +
	"\n" +
	"UpdateRole\x12\x1f.authlayer.v1.UpdateRoleRequest\x1a .authlayer.v1.UpdateRoleResponse\x12O\n" +
	"\n" +
	"DeleteRole\x12\x1f.authlayer.v1.DeleteRoleRequest\x1a .authlayer.v1.DeleteRoleResponse\x12L\n" +
	"\tListRoles\x12\x1e.authlayer.v1.ListRolesRequest\x1a\x1f.authlayer.v1.ListRolesResponse\x12O\n" +
	"\n" +
	"AssignRole\x12\x1f.authlayer.v1.AssignRoleRequest\x1a .authlayer.v1.AssignRoleResponse\x12O\n" +
	"\n" +
	"RevokeRole\x12\x1f.authlayer.v1.RevokeRoleRequest\x1a .authlayer.v1.RevokeRoleResponse\x12a\n" +
	"\x10CreatePermission\x12%.authlayer.v1.CreatePermissionRequest\x1a&.authlayer.v1.CreatePermissionResponse\x12^\n" +
	"\x0fListPermissions\x12$.authlayer.v1.ListPermissionsRequest\x1a%.authlayer.v1.ListPermissionsResponse\x12a\n" +
	"\x10AssignPermission\x12%.authlayer.v1.AssignPermissionRequest\x1a&.authlayer.v1.AssignPermissionResponse\x12a\n" +
	"\x10RevokePermission\x12%.authlayer.v1.RevokePermissionRequest\x1a&.authlayer.v1.RevokePermissionResponse\x12^\n" +
	"\x0fCheckPermission\x12$.authlayer.v1.CheckPermissionRequest\x1a%.authlayer.v1.CheckPermissionResponse\x12g\n" +
	"\x12GetUserPermissions\x12'.authlayer.v1.GetUserPermissionsRequest\x1a(.authlayer.v1.GetUserPermissionsResponseBJZHgithub.com/bernardoforcillo/authlayer/pkg/proto/authlayer/v1;authlayerv1b\x06proto3"

var (
	file_authlayer_v1_rbac_proto_rawDescOnce sync.Once
	file_authlayer_v1_rbac_proto_rawDescData []byte
)

func file_authlayer_v1_rbac_proto_rawDescGZIP() []byte {
	file_authlayer_v1_rbac_proto_rawDescOnce.Do(func() {
		file_authlayer_v1_rbac_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authlayer_v1_rbac_proto_rawDesc), len(file_authlayer_v1_rbac_proto_rawDesc)))
	})
	return file_authlayer_v1_rbac_proto_rawDescData
}

var file_authlayer_v1_rbac_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_authlayer_v1_rbac_proto_goTypes = []any{
	(*RoleInfo)(nil),                   // 0: authlayer.v1.RoleInfo
	(*PermissionInfo)(nil),             // 1: authlayer.v1.PermissionInfo
	(*CreateRoleRequest)(nil),          // 2: authlayer.v1.CreateRoleRequest
	(*CreateRoleResponse)(nil),         // 3: authlayer.v1.CreateRoleResponse
	(*GetRoleRequest)(nil),             // 4: authlayer.v1.GetRoleRequest
	(*GetRoleResponse)(nil),            // 5: authlayer.v1.GetRoleResponse
	(*UpdateRoleRequest)(nil),          // 6: authlayer.v1.UpdateRoleRequest
	(*UpdateRoleResponse)(nil),         // 7: authlayer.v1.UpdateRoleResponse
	(*DeleteRoleRequest)(nil),          // 8: authlayer.v1.DeleteRoleRequest
	(*DeleteRoleResponse)(nil),         // 9: authlayer.v1.DeleteRoleResponse
	(*ListRolesRequest)(nil),           // 10: authlayer.v1.ListRolesRequest
	(*ListRolesResponse)(nil),          // 11: authlayer.v1.ListRolesResponse
	(*AssignRoleRequest)(nil),          // 12: authlayer.v1.AssignRoleRequest
	(*AssignRoleResponse)(nil),         // 13: authlayer.v1.AssignRoleResponse
	(*RevokeRoleRequest)(nil),          // 14: authlayer.v1.RevokeRoleRequest
	(*RevokeRoleResponse)(nil),         // 15: authlayer.v1.RevokeRoleResponse
	(*CreatePermissionRequest)(nil),    // 16: authlayer.v1.CreatePermissionRequest
	(*CreatePermissionResponse)(nil),   // 17: authlayer.v1.CreatePermissionResponse
	(*ListPermissionsRequest)(nil),     // 18: authlayer.v1.ListPermissionsRequest
	(*ListPermissionsResponse)(nil),    // 19: authlayer.v1.ListPermissionsResponse
	(*AssignPermissionRequest)(nil),    // 20: authlayer.v1.AssignPermissionRequest
	(*AssignPermissionResponse)(nil),   // 21: authlayer.v1.AssignPermissionResponse
	(*RevokePermissionRequest)(nil),    // 22: authlayer.v1.RevokePermissionRequest
	(*RevokePermissionResponse)(nil),   // 23: authlayer.v1.RevokePermissionResponse
	(*CheckPermissionRequest)(nil),     // 24: authlayer.v1.CheckPermissionRequest
	(*CheckPermissionResponse)(nil),    // 25: authlayer.v1.CheckPermissionResponse
	(*GetUserPermissionsRequest)(nil),  // 26: authlayer.v1.GetUserPermissionsRequest
	(*GetUserPermissionsResponse)(nil), // 27: authlayer.v1.GetUserPermissionsResponse
	(*PaginationRequest)(nil),          // 28: authlayer.v1.PaginationRequest
	(*PaginationResponse)(nil),         // 29: authlayer.v1.PaginationResponse
}
var file_authlayer_v1_rbac_proto_depIdxs = []int32{
	1,  // 0: authlayer.v1.RoleInfo.permissions:type_name -> authlayer.v1.PermissionInfo
	0,  // 1: authlayer.v1.CreateRoleResponse.role:type_name -> authlayer.v1.RoleInfo
	0,  // 2: authlayer.v1.GetRoleResponse.role:type_name -> authlayer.v1.RoleInfo
	1,  // 3: authlayer.v1.GetRoleResponse.inherited_permissions:type_name -> authlayer.v1.PermissionInfo
	0,  // 4: authlayer.v1.UpdateRoleResponse.role:type_name -> authlayer.v1.RoleInfo
	28, // 5: authlayer.v1.ListRolesRequest.pagination:type_name -> authlayer.v1.PaginationRequest
	0,  // 6: authlayer.v1.ListRolesResponse.roles:type_name -> authlayer.v1.RoleInfo
	29, // 7: authlayer.v1.ListRolesResponse.pagination:type_name -> authlayer.v1.PaginationResponse
	1,  // 8: authlayer.v1.CreatePermissionResponse.permission:type_name -> authlayer.v1.PermissionInfo
	28, // 9: authlayer.v1.ListPermissionsRequest.pagination:type_name -> authlayer.v1.PaginationRequest
	1,  // 10: authlayer.v1.ListPermissionsResponse.permissions:type_name -> authlayer.v1.PermissionInfo
	29, // 11: authlayer.v1.ListPermissionsResponse.pagination:type_name -> authlayer.v1.PaginationResponse
	1,  // 12: authlayer.v1.GetUserPermissionsResponse.permissions:type_name -> authlayer.v1.PermissionInfo
	2,  // 13: authlayer.v1.RBACService.CreateRole:input_type -> authlayer.v1.CreateRoleRequest
	4,  // 14: authlayer.v1.RBACService.GetRole:input_type -> authlayer.v1.GetRoleRequest
	6,  // 15: authlayer.v1.RBACService.UpdateRole:input_type -> authlayer.v1.UpdateRoleRequest
	8,  // 16: authlayer.v1.RBACService.DeleteRole:input_type -> authlayer.v1.DeleteRoleRequest
	10, // 17: authlayer.v1.RBACService.ListRoles:input_type -> authlayer.v1.ListRolesRequest
	12, // 18: authlayer.v1.RBACService.AssignRole:input_type -> authlayer.v1.AssignRoleRequest
	14, // 19: authlayer.v1.RBACService.RevokeRole:input_type -> authlayer.v1.RevokeRoleRequest
	16, // 20: authlayer.v1.RBACService.CreatePermission:input_type -> authlayer.v1.CreatePermissionRequest
	18, // 21: authlayer.v1.RBACService.ListPermissions:input_type -> authlayer.v1.ListPermissionsRequest
	20, // 22: authlayer.v1.RBACService.AssignPermission:input_type -> authlayer.v1.AssignPermissionRequest
	22, // 23: authlayer.v1.RBACService.RevokePermission:input_type -> authlayer.v1.RevokePermissionRequest
	24, // 24: authlayer.v1.RBACService.CheckPermission:input_type -> authlayer.v1.CheckPermissionRequest
	26, // 25: authlayer.v1.RBACService.GetUserPermissions:input_type -> authlayer.v1.GetUserPermissionsRequest
	3,  // 26: authlayer.v1.RBACService.CreateRole:output_type -> authlayer.v1.CreateRoleResponse
	5,  // 27: authlayer.v1.RBACService.GetRole:output_type -> authlayer.v1.GetRoleResponse
	7,  // 28: authlayer.v1.RBACService.UpdateRole:output_type -> authlayer.v1.UpdateRoleResponse
	9,  // 29: authlayer.v1.RBACService.DeleteRole:output_type -> authlayer.v1.DeleteRoleResponse
	11, // 30: authlayer.v1.RBACService.ListRoles:output_type -> authlayer.v1.ListRolesResponse
	13, // 31: authlayer.v1.RBACService.AssignRole:output_type -> authlayer.v1.AssignRoleResponse
	15, // 32: authlayer.v1.RBACService.RevokeRole:output_type -> authlayer.v1.RevokeRoleResponse
	17, // 33: authlayer.v1.RBACService.CreatePermission:output_type -> authlayer.v1.CreatePermissionResponse
	19, // 34: authlayer.v1.RBACService.ListPermissions:output_type -> authlayer.v1.ListPermissionsResponse
	21, // 35: authlayer.v1.RBACService.AssignPermission:output_type -> authlayer.v1.AssignPermissionResponse
	23, // 36: authlayer.v1.RBACService.RevokePermission:output_type -> authlayer.v1.RevokePermissionResponse
	25, // 37: authlayer.v1.RBACService.CheckPermission:output_type -> authlayer.v1.CheckPermissionResponse
	27, // 38: authlayer.v1.RBACService.GetUserPermissions:output_type -> authlayer.v1.GetUserPermissionsResponse
	26, // [26:39] is the sub-list for method output_type
	13, // [13:26] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_authlayer_v1_rbac_proto_init() }
func file_authlayer_v1_rbac_proto_init() {
	if File_authlayer_v1_rbac_proto != nil {
		return
	}
	file_authlayer_v1_common_proto_init()
	file_authlayer_v1_rbac_proto_msgTypes[0].OneofWrappers = []any{}
	file_authlayer_v1_rbac_proto_msgTypes[1].OneofWrappers = []any{}
	file_authlayer_v1_rbac_proto_msgTypes[2].OneofWrappers = []any{}
	file_authlayer_v1_rbac_proto_msgTypes[6].OneofWrappers = []any{}
	file_authlayer_v1_rbac_proto_msgTypes[10].OneofWrappers = []any{}
	file_authlayer_v1_rbac_proto_msgTypes[12].OneofWrappers = []any{
		(*AssignRoleRequest_OrgId)(nil),
		(*AssignRoleRequest_TeamId)(nil),
	}
	file_authlayer_v1_rbac_proto_msgTypes[14].OneofWrappers = []any{
		(*RevokeRoleRequest_OrgId)(nil),
		(*RevokeRoleRequest_TeamId)(nil),
	}
	file_authlayer_v1_rbac_proto_msgTypes[16].OneofWrappers = []any{}
	file_authlayer_v1_rbac_proto_msgTypes[24].OneofWrappers = []any{}
	file_authlayer_v1_rbac_proto_msgTypes[26].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authlayer_v1_rbac_proto_rawDesc), len(file_authlayer_v1_rbac_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authlayer_v1_rbac_proto_goTypes,
		DependencyIndexes: file_authlayer_v1_rbac_proto_depIdxs,
		MessageInfos:      file_authlayer_v1_rbac_proto_msgTypes,
	}.Build()
	File_authlayer_v1_rbac_proto = out.File
	file_authlayer_v1_rbac_proto_goTypes = nil
	file_authlayer_v1_rbac_proto_depIdxs = nil
}
