// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: authlayer/v1/service_account.proto

package authlayerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceAccountStatus int32

const (
	ServiceAccountStatus_SERVICE_ACCOUNT_STATUS_UNSPECIFIED ServiceAccountStatus = 0
	ServiceAccountStatus_SERVICE_ACCOUNT_STATUS_ACTIVE      ServiceAccountStatus = 1
	ServiceAccountStatus_SERVICE_ACCOUNT_STATUS_DISABLED    ServiceAccountStatus = 2
)

// Enum value maps for ServiceAccountStatus.
var (
	ServiceAccountStatus_name = map[int32]string{
		0: "SERVICE_ACCOUNT_STATUS_UNSPECIFIED",
		1: "SERVICE_ACCOUNT_STATUS_ACTIVE",
		2: "SERVICE_ACCOUNT_STATUS_DISABLED",
	}
	ServiceAccountStatus_value = map[string]int32{
		"SERVICE_ACCOUNT_STATUS_UNSPECIFIED": 0,
		"SERVICE_ACCOUNT_STATUS_ACTIVE":      1,
		"SERVICE_ACCOUNT_STATUS_DISABLED":    2,
	}
)

func (x ServiceAccountStatus) Enum() *ServiceAccountStatus {
	p := new(ServiceAccountStatus)
	*p = x
	return p
}

func (x ServiceAccountStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceAccountStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_authlayer_v1_service_account_proto_enumTypes[0].Descriptor()
}

func (ServiceAccountStatus) Type() protoreflect.EnumType {
	return &file_authlayer_v1_service_account_proto_enumTypes[0]
}

func (x ServiceAccountStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceAccountStatus.Descriptor instead.
func (ServiceAccountStatus) EnumDescriptor() ([]byte, []int) {
	return file_authlayer_v1_service_account_proto_rawDescGZIP(), []int{0}
}

type ServiceAccountInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName         string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description         string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	OrgId               string                 `protobuf:"bytes,4,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	CreatedBy           string                 `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Status              ServiceAccountStatus   `protobuf:"varint,6,opt,name=status,proto3,enum=authlayer.v1.ServiceAccountStatus" json:"status,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastAuthenticatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_authenticated_at,json=lastAuthenticatedAt,proto3,oneof" json:"last_authenticated_at,omitempty"`
	Roles               []*RoleInfo            `protobuf:"bytes,10,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ServiceAccountInfo) Reset() {
	*x = ServiceAccountInfo{}
	mi := &file_authlayer_v1_service_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceAccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAccountInfo) ProtoMessage() {}

func (x *ServiceAccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_service_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAccountInfo.ProtoReflect.Descriptor instead.
func (*ServiceAccountInfo) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_service_account_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceAccountInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceAccountInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ServiceAccountInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ServiceAccountInfo) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ServiceAccountInfo) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *ServiceAccountInfo) GetStatus() ServiceAccountStatus {
	if x != nil {
		return x.Status
	}
	return ServiceAccountStatus_SERVICE_ACCOUNT_STATUS_UNSPECIFIED
}

func (x *ServiceAccountInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ServiceAccountInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ServiceAccountInfo) GetLastAuthenticatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAuthenticatedAt
	}
	return nil
}

func (x *ServiceAccountInfo) GetRoles() []*RoleInfo {
	if x != nil {
		return x.Roles
	}
	return nil
}

type ServiceAccountKeyInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceAccountId string                 `protobuf:"bytes,2,opt,name=service_account_id,json=serviceAccountId,proto3" json:"service_account_id,omitempty"`
	KeyPrefix        string                 `protobuf:"bytes,3,opt,name=key_prefix,json=keyPrefix,proto3" json:"key_prefix,omitempty"`
	Name             string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	LastUsedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_used_at,json=lastUsedAt,proto3,oneof" json:"last_used_at,omitempty"`
	Revoked          bool                   `protobuf:"varint,8,opt,name=revoked,proto3" json:"revoked,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ServiceAccountKeyInfo) Reset() {
	*x = ServiceAccountKeyInfo{}
	mi := &file_authlayer_v1_service_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceAccountKeyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAccountKeyInfo) ProtoMessage() {}

func (x *ServiceAccountKeyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_service_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAccountKeyInfo.ProtoReflect.Descriptor instead.
func (*ServiceAccountKeyInfo) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_service_account_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceAccountKeyInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceAccountKeyInfo) GetServiceAccountId() string {
	if x != nil {
		return x.ServiceAccountId
	}
	return ""
}

func (x *ServiceAccountKeyInfo) GetKeyPrefix() string {
	if x != nil {
		return x.KeyPrefix
	}
	return ""
}

func (x *ServiceAccountKeyInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceAccountKeyInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ServiceAccountKeyInfo) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ServiceAccountKeyInfo) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

func (x *ServiceAccountKeyInfo) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

type CreateServiceAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayName   string                 `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	OrgId         string                 `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServiceAccountRequest) Reset() {
	*x = CreateServiceAccountRequest{}
	mi := &file_authlayer_v1_service_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceAccountRequest) ProtoMessage() {}

func (x *CreateServiceAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_service_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateServiceAccountRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_service_account_proto_rawDescGZIP(), []int{2}
}

func (x *CreateServiceAccountRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateServiceAccountRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateServiceAccountRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type CreateServiceAccountResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceAccount *ServiceAccountInfo    `protobuf:"bytes,1,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateServiceAccountResponse) Reset() {
	*x = CreateServiceAccountResponse{}
	mi := &file_authlayer_v1_service_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceAccountResponse) ProtoMessage() {}

func (x *CreateServiceAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_service_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateServiceAccountResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_service_account_proto_rawDescGZIP(), []int{3}
}

func (x *CreateServiceAccountResponse) GetServiceAccount() *ServiceAccountInfo {
	if x != nil {
		return x.ServiceAccount
	}
	return nil
}

type GetServiceAccountRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServiceAccountId string                 `protobuf:"bytes,1,opt,name=service_account_id,json=serviceAccountId,proto3" json:"service_account_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetServiceAccountRequest) Reset() {
	*x = GetServiceAccountRequest{}
	mi := &file_authlayer_v1_service_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceAccountRequest) ProtoMessage() {}

func (x *GetServiceAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_service_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceAccountRequest.ProtoReflect.Descriptor instead.
func (*GetServiceAccountRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_service_account_proto_rawDescGZIP(), []int{4}
}

func (x *GetServiceAccountRequest) GetServiceAccountId() string {
	if x != nil {
		return x.ServiceAccountId
	}
	return ""
}

type GetServiceAccountResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceAccount *ServiceAccountInfo    `protobuf:"bytes,1,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetServiceAccountResponse) Reset() {
	*x = GetServiceAccountResponse{}
	mi := &file_authlayer_v1_service_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceAccountResponse) ProtoMessage() {}

func (x *GetServiceAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_service_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceAccountResponse.ProtoReflect.Descriptor instead.
func (*GetServiceAccountResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_service_account_proto_rawDescGZIP(), []int{5}
}

func (x *GetServiceAccountResponse) GetServiceAccount() *ServiceAccountInfo {
	if x != nil {
		return x.ServiceAccount
	}
	return nil
}

type UpdateServiceAccountRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServiceAccountId string                 `protobuf:"bytes,1,opt,name=service_account_id,json=serviceAccountId,proto3" json:"service_account_id,omitempty"`
	DisplayName      *string                `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	Description      *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Status           *ServiceAccountStatus  `protobuf:"varint,4,opt,name=status,proto3,enum=authlayer.v1.ServiceAccountStatus,oneof" json:"status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateServiceAccountRequest) Reset() {
	*x = UpdateServiceAccountRequest{}
	mi := &file_authlayer_v1_service_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServiceAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceAccountRequest) ProtoMessage() {}

func (x *UpdateServiceAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_service_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceAccountRequest.ProtoReflect.Descriptor instead.
func (*UpdateServiceAccountRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_service_account_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateServiceAccountRequest) GetServiceAccountId() string {
	if x != nil {
		return x.ServiceAccountId
	}
	return ""
}

func (x *UpdateServiceAccountRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *UpdateServiceAccountRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateServiceAccountRequest) GetStatus() ServiceAccountStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ServiceAccountStatus_SERVICE_ACCOUNT_STATUS_UNSPECIFIED
}

type UpdateServiceAccountResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceAccount *ServiceAccountInfo    `protobuf:"bytes,1,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateServiceAccountResponse) Reset() {
	*x = UpdateServiceAccountResponse{}
	mi := &file_authlayer_v1_service_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServiceAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceAccountResponse) ProtoMessage() {}

func (x *UpdateServiceAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_service_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceAccountResponse.ProtoReflect.Descriptor instead.
func (*UpdateServiceAccountResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_service_account_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateServiceAccountResponse) GetServiceAccount() *ServiceAccountInfo {
	if x != nil {
		return x.ServiceAccount
	}
	return nil
}

type DeleteServiceAccountRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServiceAccountId string                 `protobuf:"bytes,1,opt,name=service_account_id,json=serviceAccountId,proto3" json:"service_account_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeleteServiceAccountRequest) Reset() {
	*x = DeleteServiceAccountRequest{}
	mi := &file_authlayer_v1_service_account_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServiceAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceAccountRequest) ProtoMessage() {}

func (x *DeleteServiceAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_service_account_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteServiceAccountRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_service_account_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteServiceAccountRequest) GetServiceAccountId() string {
	if x != nil {
		return x.ServiceAccountId
	}
	return ""
}

type DeleteServiceAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServiceAccountResponse) Reset() {
	*x = DeleteServiceAccountResponse{}
	mi := &file_authlayer_v1_service_account_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServiceAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceAccountResponse) ProtoMessage() {}

func (x *DeleteServiceAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_service_account_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceAccountResponse.ProtoReflect.Descriptor instead.
func (*DeleteServiceAccountResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_service_account_proto_rawDescGZIP(), []int{9}
}

type ListServiceAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Pagination    *PaginationRequest     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServiceAccountsRequest) Reset() {
	*x = ListServiceAccountsRequest{}
	mi := &file_authlayer_v1_service_account_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServiceAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServiceAccountsRequest) ProtoMessage() {}

func (x *ListServiceAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_service_account_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServiceAccountsRequest.ProtoReflect.Descriptor instead.
func (*ListServiceAccountsRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_service_account_proto_rawDescGZIP(), []int{10}
}

func (x *ListServiceAccountsRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ListServiceAccountsRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListServiceAccountsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServiceAccounts []*ServiceAccountInfo  `protobuf:"bytes,1,rep,name=service_accounts,json=serviceAccounts,proto3" json:"service_accounts,omitempty"`
	Pagination      *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListServiceAccountsResponse) Reset() {
	*x = ListServiceAccountsResponse{}
	mi := &file_authlayer_v1_service_account_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServiceAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServiceAccountsResponse) ProtoMessage() {}

func (x *ListServiceAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_service_account_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServiceAccountsResponse.ProtoReflect.Descriptor instead.
func (*ListServiceAccountsResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_service_account_proto_rawDescGZIP(), []int{11}
}

func (x *ListServiceAccountsResponse) GetServiceAccounts() []*ServiceAccountInfo {
	if x != nil {
		return x.ServiceAccounts
	}
	return nil
}

func (x *ListServiceAccountsResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type CreateServiceAccountKeyRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServiceAccountId string                 `protobuf:"bytes,1,opt,name=service_account_id,json=serviceAccountId,proto3" json:"service_account_id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ExpiresAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateServiceAccountKeyRequest) Reset() {
	*x = CreateServiceAccountKeyRequest{}
	mi := &file_authlayer_v1_service_account_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceAccountKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceAccountKeyRequest) ProtoMessage() {}

func (x *CreateServiceAccountKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_service_account_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceAccountKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateServiceAccountKeyRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_service_account_proto_rawDescGZIP(), []int{12}
}

func (x *CreateServiceAccountKeyRequest) GetServiceAccountId() string {
	if x != nil {
		return x.ServiceAccountId
	}
	return ""
}

func (x *CreateServiceAccountKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateServiceAccountKeyRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type CreateServiceAccountKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyInfo       *ServiceAccountKeyInfo `protobuf:"bytes,1,opt,name=key_info,json=keyInfo,proto3" json:"key_info,omitempty"`
	PlainTextKey  string                 `protobuf:"bytes,2,opt,name=plain_text_key,json=plainTextKey,proto3" json:"plain_text_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServiceAccountKeyResponse) Reset() {
	*x = CreateServiceAccountKeyResponse{}
	mi := &file_authlayer_v1_service_account_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceAccountKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceAccountKeyResponse) ProtoMessage() {}

func (x *CreateServiceAccountKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_service_account_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceAccountKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateServiceAccountKeyResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_service_account_proto_rawDescGZIP(), []int{13}
}

func (x *CreateServiceAccountKeyResponse) GetKeyInfo() *ServiceAccountKeyInfo {
	if x != nil {
		return x.KeyInfo
	}
	return nil
}

func (x *CreateServiceAccountKeyResponse) GetPlainTextKey() string {
	if x != nil {
		return x.PlainTextKey
	}
	return ""
}

type RevokeServiceAccountKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeServiceAccountKeyRequest) Reset() {
	*x = RevokeServiceAccountKeyRequest{}
	mi := &file_authlayer_v1_service_account_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeServiceAccountKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeServiceAccountKeyRequest) ProtoMessage() {}

func (x *RevokeServiceAccountKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_service_account_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeServiceAccountKeyRequest.ProtoReflect.Descriptor instead.
func (*RevokeServiceAccountKeyRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_service_account_proto_rawDescGZIP(), []int{14}
}

func (x *RevokeServiceAccountKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type RevokeServiceAccountKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeServiceAccountKeyResponse) Reset() {
	*x = RevokeServiceAccountKeyResponse{}
	mi := &file_authlayer_v1_service_account_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeServiceAccountKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeServiceAccountKeyResponse) ProtoMessage() {}

func (x *RevokeServiceAccountKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_service_account_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeServiceAccountKeyResponse.ProtoReflect.Descriptor instead.
func (*RevokeServiceAccountKeyResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_service_account_proto_rawDescGZIP(), []int{15}
}

type ListServiceAccountKeysRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServiceAccountId string                 `protobuf:"bytes,1,opt,name=service_account_id,json=serviceAccountId,proto3" json:"service_account_id,omitempty"`
	Pagination       *PaginationRequest     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListServiceAccountKeysRequest) Reset() {
	*x = ListServiceAccountKeysRequest{}
	mi := &file_authlayer_v1_service_account_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServiceAccountKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServiceAccountKeysRequest) ProtoMessage() {}

func (x *ListServiceAccountKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_service_account_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServiceAccountKeysRequest.ProtoReflect.Descriptor instead.
func (*ListServiceAccountKeysRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_service_account_proto_rawDescGZIP(), []int{16}
}

func (x *ListServiceAccountKeysRequest) GetServiceAccountId() string {
	if x != nil {
		return x.ServiceAccountId
	}
	return ""
}

func (x *ListServiceAccountKeysRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListServiceAccountKeysResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Keys          []*ServiceAccountKeyInfo `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Pagination    *PaginationResponse      `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServiceAccountKeysResponse) Reset() {
	*x = ListServiceAccountKeysResponse{}
	mi := &file_authlayer_v1_service_account_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServiceAccountKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServiceAccountKeysResponse) ProtoMessage() {}

func (x *ListServiceAccountKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_service_account_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServiceAccountKeysResponse.ProtoReflect.Descriptor instead.
func (*ListServiceAccountKeysResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_service_account_proto_rawDescGZIP(), []int{17}
}

func (x *ListServiceAccountKeysResponse) GetKeys() []*ServiceAccountKeyInfo {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *ListServiceAccountKeysResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type AssignServiceAccountRoleRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServiceAccountId string                 `protobuf:"bytes,1,opt,name=service_account_id,json=serviceAccountId,proto3" json:"service_account_id,omitempty"`
	RoleId           string                 `protobuf:"bytes,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	OrgId            string                 `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AssignServiceAccountRoleRequest) Reset() {
	*x = AssignServiceAccountRoleRequest{}
	mi := &file_authlayer_v1_service_account_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignServiceAccountRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignServiceAccountRoleRequest) ProtoMessage() {}

func (x *AssignServiceAccountRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_service_account_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignServiceAccountRoleRequest.ProtoReflect.Descriptor instead.
func (*AssignServiceAccountRoleRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_service_account_proto_rawDescGZIP(), []int{18}
}

func (x *AssignServiceAccountRoleRequest) GetServiceAccountId() string {
	if x != nil {
		return x.ServiceAccountId
	}
	return ""
}

func (x *AssignServiceAccountRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *AssignServiceAccountRoleRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type AssignServiceAccountRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignServiceAccountRoleResponse) Reset() {
	*x = AssignServiceAccountRoleResponse{}
	mi := &file_authlayer_v1_service_account_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignServiceAccountRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignServiceAccountRoleResponse) ProtoMessage() {}

func (x *AssignServiceAccountRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_service_account_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignServiceAccountRoleResponse.ProtoReflect.Descriptor instead.
func (*AssignServiceAccountRoleResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_service_account_proto_rawDescGZIP(), []int{19}
}

type RevokeServiceAccountRoleRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServiceAccountId string                 `protobuf:"bytes,1,opt,name=service_account_id,json=serviceAccountId,proto3" json:"service_account_id,omitempty"`
	RoleId           string                 `protobuf:"bytes,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	OrgId            string                 `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RevokeServiceAccountRoleRequest) Reset() {
	*x = RevokeServiceAccountRoleRequest{}
	mi := &file_authlayer_v1_service_account_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeServiceAccountRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeServiceAccountRoleRequest) ProtoMessage() {}

func (x *RevokeServiceAccountRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_service_account_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeServiceAccountRoleRequest.ProtoReflect.Descriptor instead.
func (*RevokeServiceAccountRoleRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_service_account_proto_rawDescGZIP(), []int{20}
}

func (x *RevokeServiceAccountRoleRequest) GetServiceAccountId() string {
	if x != nil {
		return x.ServiceAccountId
	}
	return ""
}

func (x *RevokeServiceAccountRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *RevokeServiceAccountRoleRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type RevokeServiceAccountRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeServiceAccountRoleResponse) Reset() {
	*x = RevokeServiceAccountRoleResponse{}
	mi := &file_authlayer_v1_service_account_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeServiceAccountRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeServiceAccountRoleResponse) ProtoMessage() {}

func (x *RevokeServiceAccountRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_service_account_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeServiceAccountRoleResponse.ProtoReflect.Descriptor instead.
func (*RevokeServiceAccountRoleResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_service_account_proto_rawDescGZIP(), []int{21}
}

var File_authlayer_v1_service_account_proto protoreflect.FileDescriptor

const file_authlayer_v1_service_account_proto_rawDesc = "" +
	"\n" +
	"\"authlayer/v1/service_account.proto\x12\fauthlayer.v1\x1a\x19authlayer/v1/common.proto\x1a\x17authlayer/v1/rbac.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xee\x03\n" +
	"\x12ServiceAccountInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x15\n" +
	"\x06org_id\x18\x04 \x01(\tR\x05orgId\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\tR\tcreatedBy\x12:\n" +
	"\x06status\x18\x06 \x01(\x0e2\".authlayer.v1.ServiceAccountStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12S\n" +
	"\x15last_authenticated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x13lastAuthenticatedAt\x88\x01\x01\x12,\n" +
	"\x05roles\x18\n" +
	" \x03(\v2\x16.authlayer.v1.RoleInfoR\x05rolesB\x18\n" +
	"\x16_last_authenticated_at\"\x80\x03\n" +
	"\x15ServiceAccountKeyInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x12service_account_id\x18\x02 \x01(\tR\x10serviceAccountId\x12\x1d\n" +
	"\n" +
	"key_prefix\x18\x03 \x01(\tR\tkeyPrefix\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12>\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\texpiresAt\x88\x01\x01\x12A\n" +
	"\flast_used_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x01R\n" +
	"lastUsedAt\x88\x01\x01\x12\x18\n" +
	"\arevoked\x18\b \x01(\bR\arevokedB\r\n" +
	"\v_expires_atB\x0f\n" +
	"\r_last_used_at\"y\n" +
	"\x1bCreateServiceAccountRequest\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\"i\n" +
	"\x1cCreateServiceAccountResponse\x12I\n" +
	"\x0fservice_account\x18\x01 \x01(\v2 .authlayer.v1.ServiceAccountInfoR\x0eserviceAccount\"H\n" +
	"\x18GetServiceAccountRequest\x12,\n" +
	"\x12service_account_id\x18\x01 \x01(\tR\x10serviceAccountId\"f\n" +
	"\x19GetServiceAccountResponse\x12I\n" +
	"\x0fservice_account\x18\x01 \x01(\v2 .authlayer.v1.ServiceAccountInfoR\x0eserviceAccount\"\x87\x02\n" +
	"\x1bUpdateServiceAccountRequest\x12,\n" +
	"\x12service_account_id\x18\x01 \x01(\tR\x10serviceAccountId\x12&\n" +
	"\fdisplay_name\x18\x02 \x01(\tH\x00R\vdisplayName\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12?\n" +
	"\x06status\x18\x04 \x01(\x0e2\".authlayer.v1.ServiceAccountStatusH\x02R\x06status\x88\x01\x01B\x0f\n" +
	"\r_display_nameB\x0e\n" +
	"\f_descriptionB\t\n" +
	"\a_status\"i\n" +
	"\x1cUpdateServiceAccountResponse\x12I\n" +
	"\x0fservice_account\x18\x01 \x01(\v2 .authlayer.v1.ServiceAccountInfoR\x0eserviceAccount\"K\n" +
	"\x1bDeleteServiceAccountRequest\x12,\n" +
	"\x12service_account_id\x18\x01 \x01(\tR\x10serviceAccountId\"\x1e\n" +
	"\x1cDeleteServiceAccountResponse\"t\n" +
	"\x1aListServiceAccountsRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12?\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1f.authlayer.v1.PaginationRequestR\n" +
	"pagination\"\xac\x01\n" +
	"\x1bListServiceAccountsResponse\x12K\n" +
	"\x10service_accounts\x18\x01 \x03(\v2 .authlayer.v1.ServiceAccountInfoR\x0fserviceAccounts\x12@\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2 .authlayer.v1.PaginationResponseR\n" +
	"pagination\"\xb1\x01\n" +
	"\x1eCreateServiceAccountKeyRequest\x12,\n" +
	"\x12service_account_id\x18\x01 \x01(\tR\x10serviceAccountId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12>\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\texpiresAt\x88\x01\x01B\r\n" +
	"\v_expires_at\"\x87\x01\n" +
	"\x1fCreateServiceAccountKeyResponse\x12>\n" +
	"\bkey_info\x18\x01 \x01(\v2#.authlayer.v1.ServiceAccountKeyInfoR\akeyInfo\x12$\n" +
	"\x0eplain_text_key\x18\x02 \x01(\tR\fplainTextKey\"7\n" +
	"\x1eRevokeServiceAccountKeyRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\"!\n" +
	"\x1fRevokeServiceAccountKeyResponse\"\x8e\x01\n" +
	"\x1dListServiceAccountKeysRequest\x12,\n" +
	"\x12service_account_id\x18\x01 \x01(\tR\x10serviceAccountId\x12?\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1f.authlayer.v1.PaginationRequestR\n" +
	"pagination\"\x9b\x01\n" +
	"\x1eListServiceAccountKeysResponse\x127\n" +
	"\x04keys\x18\x01 \x03(\v2#.authlayer.v1.ServiceAccountKeyInfoR\x04keys\x12@\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2 .authlayer.v1.PaginationResponseR\n" +
	"pagination\"\x7f\n" +
	"\x1fAssignServiceAccountRoleRequest\x12,\n" +
	"\x12service_account_id\x18\x01 \x01(\tR\x10serviceAccountId\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\tR\x06roleId\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\"\"\n" +
	" AssignServiceAccountRoleResponse\"\x7f\n" +
	"\x1fRevokeServiceAccountRoleRequest\x12,\n" +
	"\x12service_account_id\x18\x01 \x01(\tR\x10serviceAccountId\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\tR\x06roleId\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\"\"\n" +
	" RevokeServiceAccountRoleResponse*\x86\x01\n" +
	"\x14ServiceAccountStatus\x12&\n" +
	"\"SERVICE_ACCOUNT_STATUS_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dSERVICE_ACCOUNT_STATUS_ACTIVE\x10\x01\x12#\n" +
	"\x1fSERVICE_ACCOUNT_STATUS_DISABLED\x10\x022\xf5\b\n" +
	"\x15ServiceAccountService\x12m\n" +
	"\x14CreateServiceAccount\x12).authlayer.v1.CreateServiceAccountRequest\x1a*.authlayer.v1.CreateServiceAccountResponse\x12d\n" +
	"\x11GetServiceAccount\x12&.authlayer.v1.GetServiceAccountRequest\x1a'.authlayer.v1.GetServiceAccountResponse\x12m\n" +
	"\x14UpdateServiceAccount\x12).authlayer.v1.UpdateServiceAccountRequest\x1a*.authlayer.v1.UpdateServiceAccountResponse\x12m\n" +
	"\x14DeleteServiceAccount\x12).authlayer.v1.DeleteServiceAccountRequest\x1a*.authlayer.v1.DeleteServiceAccountResponse\x12j\n" +
	"\x13ListServiceAccounts\x12(.authlayer.v1.ListServiceAccountsRequest\x1a).authlayer.v1.ListServiceAccountsResponse\x12v\n" +
	"\x17CreateServiceAccountKey\x12,.authlayer.v1.CreateServiceAccountKeyRequest\x1a-.authlayer.v1.CreateServiceAccountKeyResponse\x12v\n" +
	"\x17RevokeServiceAccountKey\x12,.authlayer.v1.RevokeServiceAccountKeyRequest\x1a-.authlayer.v1.RevokeServiceAccountKeyResponse\x12s\n" +
	"\x16ListServiceAccountKeys\x12+.authlayer.v1.ListServiceAccountKeysRequest\x1a,.authlayer.v1.ListServiceAccountKeysResponse\x12k\n" +
	"\n" +
	"AssignRole\x12-.authlayer.v1.AssignServiceAccountRoleRequest\x1a..authlayer.v1.AssignServiceAccountRoleResponse\x12k\n" +
	"\n" +
	"RevokeRole\x12-.authlayer.v1.RevokeServiceAccountRoleRequest\x1a..authlayer.v1.RevokeServiceAccountRoleResponseBJZHgithub.com/bernardoforcillo/authlayer/pkg/proto/authlayer/v1;authlayerv1b\x06proto3"

var (
	file_authlayer_v1_service_account_proto_rawDescOnce sync.Once
	file_authlayer_v1_service_account_proto_rawDescData []byte
)

func file_authlayer_v1_service_account_proto_rawDescGZIP() []byte {
	file_authlayer_v1_service_account_proto_rawDescOnce.Do(func() {
		file_authlayer_v1_service_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authlayer_v1_service_account_proto_rawDesc), len(file_authlayer_v1_service_account_proto_rawDesc)))
	})
	return file_authlayer_v1_service_account_proto_rawDescData
}

var file_authlayer_v1_service_account_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_authlayer_v1_service_account_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_authlayer_v1_service_account_proto_goTypes = []any{
	(ServiceAccountStatus)(0),                // 0: authlayer.v1.ServiceAccountStatus
	(*ServiceAccountInfo)(nil),               // 1: authlayer.v1.ServiceAccountInfo
	(*ServiceAccountKeyInfo)(nil),            // 2: authlayer.v1.ServiceAccountKeyInfo
	(*CreateServiceAccountRequest)(nil),      // 3: authlayer.v1.CreateServiceAccountRequest
	(*CreateServiceAccountResponse)(nil),     // 4: authlayer.v1.CreateServiceAccountResponse
	(*GetServiceAccountRequest)(nil),         // 5: authlayer.v1.GetServiceAccountRequest
	(*GetServiceAccountResponse)(nil),        // 6: authlayer.v1.GetServiceAccountResponse
	(*UpdateServiceAccountRequest)(nil),      // 7: authlayer.v1.UpdateServiceAccountRequest
	(*UpdateServiceAccountResponse)(nil),     // 8: authlayer.v1.UpdateServiceAccountResponse
	(*DeleteServiceAccountRequest)(nil),      // 9: authlayer.v1.DeleteServiceAccountRequest
	(*DeleteServiceAccountResponse)(nil),     // 10: authlayer.v1.DeleteServiceAccountResponse
	(*ListServiceAccountsRequest)(nil),       // 11: authlayer.v1.ListServiceAccountsRequest
	(*ListServiceAccountsResponse)(nil),      // 12: authlayer.v1.ListServiceAccountsResponse
	(*CreateServiceAccountKeyRequest)(nil),   // 13: authlayer.v1.CreateServiceAccountKeyRequest
	(*CreateServiceAccountKeyResponse)(nil),  // 14: authlayer.v1.CreateServiceAccountKeyResponse
	(*RevokeServiceAccountKeyRequest)(nil),   // 15: authlayer.v1.RevokeServiceAccountKeyRequest
	(*RevokeServiceAccountKeyResponse)(nil),  // 16: authlayer.v1.RevokeServiceAccountKeyResponse
	(*ListServiceAccountKeysRequest)(nil),    // 17: authlayer.v1.ListServiceAccountKeysRequest
	(*ListServiceAccountKeysResponse)(nil),   // 18: authlayer.v1.ListServiceAccountKeysResponse
	(*AssignServiceAccountRoleRequest)(nil),  // 19: authlayer.v1.AssignServiceAccountRoleRequest
	(*AssignServiceAccountRoleResponse)(nil), // 20: authlayer.v1.AssignServiceAccountRoleResponse
	(*RevokeServiceAccountRoleRequest)(nil),  // 21: authlayer.v1.RevokeServiceAccountRoleRequest
	(*RevokeServiceAccountRoleResponse)(nil), // 22: authlayer.v1.RevokeServiceAccountRoleResponse
	(*timestamppb.Timestamp)(nil),            // 23: google.protobuf.Timestamp
	(*RoleInfo)(nil),                         // 24: authlayer.v1.RoleInfo
	(*PaginationRequest)(nil),                // 25: authlayer.v1.PaginationRequest
	(*PaginationResponse)(nil),               // 26: authlayer.v1.PaginationResponse
}
var file_authlayer_v1_service_account_proto_depIdxs = []int32{
	0,  // 0: authlayer.v1.ServiceAccountInfo.status:type_name -> authlayer.v1.ServiceAccountStatus
	23, // 1: authlayer.v1.ServiceAccountInfo.created_at:type_name -> google.protobuf.Timestamp
	23, // 2: authlayer.v1.ServiceAccountInfo.updated_at:type_name -> google.protobuf.Timestamp
	23, // 3: authlayer.v1.ServiceAccountInfo.last_authenticated_at:type_name -> google.protobuf.Timestamp
	24, // 4: authlayer.v1.ServiceAccountInfo.roles:type_name -> authlayer.v1.RoleInfo
	23, // 5: authlayer.v1.ServiceAccountKeyInfo.created_at:type_name -> google.protobuf.Timestamp
	23, // 6: authlayer.v1.ServiceAccountKeyInfo.expires_at:type_name -> google.protobuf.Timestamp
	23, // 7: authlayer.v1.ServiceAccountKeyInfo.last_used_at:type_name -> google.protobuf.Timestamp
	1,  // 8: authlayer.v1.CreateServiceAccountResponse.service_account:type_name -> authlayer.v1.ServiceAccountInfo
	1,  // 9: authlayer.v1.GetServiceAccountResponse.service_account:type_name -> authlayer.v1.ServiceAccountInfo
	0,  // 10: authlayer.v1.UpdateServiceAccountRequest.status:type_name -> authlayer.v1.ServiceAccountStatus
	1,  // 11: authlayer.v1.UpdateServiceAccountResponse.service_account:type_name -> authlayer.v1.ServiceAccountInfo
	25, // 12: authlayer.v1.ListServiceAccountsRequest.pagination:type_name -> authlayer.v1.PaginationRequest
	1,  // 13: authlayer.v1.ListServiceAccountsResponse.service_accounts:type_name -> authlayer.v1.ServiceAccountInfo
	26, // 14: authlayer.v1.ListServiceAccountsResponse.pagination:type_name -> authlayer.v1.PaginationResponse
	23, // 15: authlayer.v1.CreateServiceAccountKeyRequest.expires_at:type_name -> google.protobuf.Timestamp
	2,  // 16: authlayer.v1.CreateServiceAccountKeyResponse.key_info:type_name -> authlayer.v1.ServiceAccountKeyInfo
	25, // 17: authlayer.v1.ListServiceAccountKeysRequest.pagination:type_name -> authlayer.v1.PaginationRequest
	2,  // 18: authlayer.v1.ListServiceAccountKeysResponse.keys:type_name -> authlayer.v1.ServiceAccountKeyInfo
	26, // 19: authlayer.v1.ListServiceAccountKeysResponse.pagination:type_name -> authlayer.v1.PaginationResponse
	3,  // 20: authlayer.v1.ServiceAccountService.CreateServiceAccount:input_type -> authlayer.v1.CreateServiceAccountRequest
	5,  // 21: authlayer.v1.ServiceAccountService.GetServiceAccount:input_type -> authlayer.v1.GetServiceAccountRequest
	7,  // 22: authlayer.v1.ServiceAccountService.UpdateServiceAccount:input_type -> authlayer.v1.UpdateServiceAccountRequest
	9,  // 23: authlayer.v1.ServiceAccountService.DeleteServiceAccount:input_type -> authlayer.v1.DeleteServiceAccountRequest
	11, // 24: authlayer.v1.ServiceAccountService.ListServiceAccounts:input_type -> authlayer.v1.ListServiceAccountsRequest
	13, // 25: authlayer.v1.ServiceAccountService.CreateServiceAccountKey:input_type -> authlayer.v1.CreateServiceAccountKeyRequest
	15, // 26: authlayer.v1.ServiceAccountService.RevokeServiceAccountKey:input_type -> authlayer.v1.RevokeServiceAccountKeyRequest
	17, // 27: authlayer.v1.ServiceAccountService.ListServiceAccountKeys:input_type -> authlayer.v1.ListServiceAccountKeysRequest
	19, // 28: authlayer.v1.ServiceAccountService.AssignRole:input_type -> authlayer.v1.AssignServiceAccountRoleRequest
	21, // 29: authlayer.v1.ServiceAccountService.RevokeRole:input_type -> authlayer.v1.RevokeServiceAccountRoleRequest
	4,  // 30: authlayer.v1.ServiceAccountService.CreateServiceAccount:output_type -> authlayer.v1.CreateServiceAccountResponse
	6,  // 31: authlayer.v1.ServiceAccountService.GetServiceAccount:output_type -> authlayer.v1.GetServiceAccountResponse
	8,  // 32: authlayer.v1.ServiceAccountService.UpdateServiceAccount:output_type -> authlayer.v1.UpdateServiceAccountResponse
	10, // 33: authlayer.v1.ServiceAccountService.DeleteServiceAccount:output_type -> authlayer.v1.DeleteServiceAccountResponse
	12, // 34: authlayer.v1.ServiceAccountService.ListServiceAccounts:output_type -> authlayer.v1.ListServiceAccountsResponse
	14, // 35: authlayer.v1.ServiceAccountService.CreateServiceAccountKey:output_type -> authlayer.v1.CreateServiceAccountKeyResponse
	16, // 36: authlayer.v1.ServiceAccountService.RevokeServiceAccountKey:output_type -> authlayer.v1.RevokeServiceAccountKeyResponse
	18, // 37: authlayer.v1.ServiceAccountService.ListServiceAccountKeys:output_type -> authlayer.v1.ListServiceAccountKeysResponse
	20, // 38: authlayer.v1.ServiceAccountService.AssignRole:output_type -> authlayer.v1.AssignServiceAccountRoleResponse
	22, // 39: authlayer.v1.ServiceAccountService.RevokeRole:output_type -> authlayer.v1.RevokeServiceAccountRoleResponse
	30, // [30:40] is the sub-list for method output_type
	20, // [20:30] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_authlayer_v1_service_account_proto_init() }
func file_authlayer_v1_service_account_proto_init() {
	if File_authlayer_v1_service_account_proto != nil {
		return
	}
	file_authlayer_v1_common_proto_init()
	file_authlayer_v1_rbac_proto_init()
	file_authlayer_v1_service_account_proto_msgTypes[0].OneofWrappers = []any{}
	file_authlayer_v1_service_account_proto_msgTypes[1].OneofWrappers = []any{}
	file_authlayer_v1_service_account_proto_msgTypes[6].OneofWrappers = []any{}
	file_authlayer_v1_service_account_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authlayer_v1_service_account_proto_rawDesc), len(file_authlayer_v1_service_account_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authlayer_v1_service_account_proto_goTypes,
		DependencyIndexes: file_authlayer_v1_service_account_proto_depIdxs,
		EnumInfos:         file_authlayer_v1_service_account_proto_enumTypes,
		MessageInfos:      file_authlayer_v1_service_account_proto_msgTypes,
	}.Build()
	File_authlayer_v1_service_account_proto = out.File
	file_authlayer_v1_service_account_proto_goTypes = nil
	file_authlayer_v1_service_account_proto_depIdxs = nil
}
