// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: authlayer/v1/team.proto

package authlayerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TeamInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OrgId         string                 `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	MemberCount   int32                  `protobuf:"varint,4,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamInfo) Reset() {
	*x = TeamInfo{}
	mi := &file_authlayer_v1_team_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamInfo) ProtoMessage() {}

func (x *TeamInfo) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_team_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamInfo.ProtoReflect.Descriptor instead.
func (*TeamInfo) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_team_proto_rawDescGZIP(), []int{0}
}

func (x *TeamInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TeamInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TeamInfo) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *TeamInfo) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

type CreateTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeamRequest) Reset() {
	*x = CreateTeamRequest{}
	mi := &file_authlayer_v1_team_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamRequest) ProtoMessage() {}

func (x *CreateTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_team_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamRequest.ProtoReflect.Descriptor instead.
func (*CreateTeamRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_team_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTeamRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *CreateTeamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Team          *TeamInfo              `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeamResponse) Reset() {
	*x = CreateTeamResponse{}
	mi := &file_authlayer_v1_team_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamResponse) ProtoMessage() {}

func (x *CreateTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_team_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamResponse.ProtoReflect.Descriptor instead.
func (*CreateTeamResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_team_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTeamResponse) GetTeam() *TeamInfo {
	if x != nil {
		return x.Team
	}
	return nil
}

type GetTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamRequest) Reset() {
	*x = GetTeamRequest{}
	mi := &file_authlayer_v1_team_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamRequest) ProtoMessage() {}

func (x *GetTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_team_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamRequest.ProtoReflect.Descriptor instead.
func (*GetTeamRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_team_proto_rawDescGZIP(), []int{3}
}

func (x *GetTeamRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type GetTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Team          *TeamInfo              `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamResponse) Reset() {
	*x = GetTeamResponse{}
	mi := &file_authlayer_v1_team_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamResponse) ProtoMessage() {}

func (x *GetTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_team_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamResponse.ProtoReflect.Descriptor instead.
func (*GetTeamResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_team_proto_rawDescGZIP(), []int{4}
}

func (x *GetTeamResponse) GetTeam() *TeamInfo {
	if x != nil {
		return x.Team
	}
	return nil
}

type UpdateTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTeamRequest) Reset() {
	*x = UpdateTeamRequest{}
	mi := &file_authlayer_v1_team_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeamRequest) ProtoMessage() {}

func (x *UpdateTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_team_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeamRequest.ProtoReflect.Descriptor instead.
func (*UpdateTeamRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_team_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateTeamRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *UpdateTeamRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type UpdateTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Team          *TeamInfo              `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTeamResponse) Reset() {
	*x = UpdateTeamResponse{}
	mi := &file_authlayer_v1_team_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeamResponse) ProtoMessage() {}

func (x *UpdateTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_team_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeamResponse.ProtoReflect.Descriptor instead.
func (*UpdateTeamResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_team_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTeamResponse) GetTeam() *TeamInfo {
	if x != nil {
		return x.Team
	}
	return nil
}

type DeleteTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTeamRequest) Reset() {
	*x = DeleteTeamRequest{}
	mi := &file_authlayer_v1_team_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamRequest) ProtoMessage() {}

func (x *DeleteTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_team_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeamRequest.ProtoReflect.Descriptor instead.
func (*DeleteTeamRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_team_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteTeamRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type DeleteTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTeamResponse) Reset() {
	*x = DeleteTeamResponse{}
	mi := &file_authlayer_v1_team_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamResponse) ProtoMessage() {}

func (x *DeleteTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_team_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeamResponse.ProtoReflect.Descriptor instead.
func (*DeleteTeamResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_team_proto_rawDescGZIP(), []int{8}
}

type ListTeamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Pagination    *PaginationRequest     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeamsRequest) Reset() {
	*x = ListTeamsRequest{}
	mi := &file_authlayer_v1_team_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamsRequest) ProtoMessage() {}

func (x *ListTeamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_team_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamsRequest.ProtoReflect.Descriptor instead.
func (*ListTeamsRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_team_proto_rawDescGZIP(), []int{9}
}

func (x *ListTeamsRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ListTeamsRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListTeamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Teams         []*TeamInfo            `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeamsResponse) Reset() {
	*x = ListTeamsResponse{}
	mi := &file_authlayer_v1_team_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamsResponse) ProtoMessage() {}

func (x *ListTeamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_team_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamsResponse.ProtoReflect.Descriptor instead.
func (*ListTeamsResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_team_proto_rawDescGZIP(), []int{10}
}

func (x *ListTeamsResponse) GetTeams() []*TeamInfo {
	if x != nil {
		return x.Teams
	}
	return nil
}

func (x *ListTeamsResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type AddTeamMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId        string                 `protobuf:"bytes,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTeamMemberRequest) Reset() {
	*x = AddTeamMemberRequest{}
	mi := &file_authlayer_v1_team_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTeamMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTeamMemberRequest) ProtoMessage() {}

func (x *AddTeamMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_team_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTeamMemberRequest.ProtoReflect.Descriptor instead.
func (*AddTeamMemberRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_team_proto_rawDescGZIP(), []int{11}
}

func (x *AddTeamMemberRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *AddTeamMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddTeamMemberRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

type AddTeamMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTeamMemberResponse) Reset() {
	*x = AddTeamMemberResponse{}
	mi := &file_authlayer_v1_team_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTeamMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTeamMemberResponse) ProtoMessage() {}

func (x *AddTeamMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_team_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTeamMemberResponse.ProtoReflect.Descriptor instead.
func (*AddTeamMemberResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_team_proto_rawDescGZIP(), []int{12}
}

type RemoveTeamMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTeamMemberRequest) Reset() {
	*x = RemoveTeamMemberRequest{}
	mi := &file_authlayer_v1_team_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTeamMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTeamMemberRequest) ProtoMessage() {}

func (x *RemoveTeamMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_team_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTeamMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveTeamMemberRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_team_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveTeamMemberRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *RemoveTeamMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RemoveTeamMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTeamMemberResponse) Reset() {
	*x = RemoveTeamMemberResponse{}
	mi := &file_authlayer_v1_team_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTeamMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTeamMemberResponse) ProtoMessage() {}

func (x *RemoveTeamMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_team_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTeamMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveTeamMemberResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_team_proto_rawDescGZIP(), []int{14}
}

type ListTeamMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Pagination    *PaginationRequest     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeamMembersRequest) Reset() {
	*x = ListTeamMembersRequest{}
	mi := &file_authlayer_v1_team_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamMembersRequest) ProtoMessage() {}

func (x *ListTeamMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_team_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamMembersRequest.ProtoReflect.Descriptor instead.
func (*ListTeamMembersRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_team_proto_rawDescGZIP(), []int{15}
}

func (x *ListTeamMembersRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *ListTeamMembersRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListTeamMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*MemberInfo          `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeamMembersResponse) Reset() {
	*x = ListTeamMembersResponse{}
	mi := &file_authlayer_v1_team_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamMembersResponse) ProtoMessage() {}

func (x *ListTeamMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_team_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamMembersResponse.ProtoReflect.Descriptor instead.
func (*ListTeamMembersResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_team_proto_rawDescGZIP(), []int{16}
}

func (x *ListTeamMembersResponse) GetMembers() []*MemberInfo {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *ListTeamMembersResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_authlayer_v1_team_proto protoreflect.FileDescriptor

const file_authlayer_v1_team_proto_rawDesc = "" +
	"\n" +
	"\x17authlayer/v1/team.proto\x12\fauthlayer.v1\x1a\x19authlayer/v1/common.proto\"h\n" +
	"\bTeamInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\x12!\n" +
	"\fmember_count\x18\x04 \x01(\x05R\vmemberCount\">\n" +
	"\x11CreateTeamRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"@\n" +
	"\x12CreateTeamResponse\x12*\n" +
	"\x04team\x18\x01 \x01(\v2\x16.authlayer.v1.TeamInfoR\x04team\")\n" +
	"\x0eGetTeamRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\"=\n" +
	"\x0fGetTeamResponse\x12*\n" +
	"\x04team\x18\x01 \x01(\v2\x16.authlayer.v1.TeamInfoR\x04team\"N\n" +
	"\x11UpdateTeamRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01B\a\n" +
	"\x05_name\"@\n" +
	"\x12UpdateTeamResponse\x12*\n" +
	"\x04team\x18\x01 \x01(\v2\x16.authlayer.v1.TeamInfoR\x04team\",\n" +
	"\x11DeleteTeamRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\"\x14\n" +
	"\x12DeleteTeamResponse\"j\n" +
	"\x10ListTeamsRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12?\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1f.authlayer.v1.PaginationRequestR\n" +
	"pagination\"\x83\x01\n" +
	"\x11ListTeamsResponse\x12,\n" +
	"\x05teams\x18\x01 \x03(\v2\x16.authlayer.v1.TeamInfoR\x05teams\x12@\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2 .authlayer.v1.PaginationResponseR\n" +
	"pagination\"a\n" +
	"\x14AddTeamMemberRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\tR\x06roleId\"\x17\n" +
	"\x15AddTeamMemberResponse\"K\n" +
	"\x17RemoveTeamMemberRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x1a\n" +
	"\x18RemoveTeamMemberResponse\"r\n" +
	"\x16ListTeamMembersRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12?\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1f.authlayer.v1.PaginationRequestR\n" +
	"pagination\"\x8f\x01\n" +
	"\x17ListTeamMembersResponse\x122\n" +
	"\amembers\x18\x01 \x03(\v2\x18.authlayer.v1.MemberInfoR\amembers\x12@\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2 .authlayer.v1.PaginationResponseR\n" +
	"pagination2\xa7\x05\n" +
	"\vTeamService\x12O\n" +
	"\n" +
	"CreateTeam\x12\x1f.authlayer.v1.CreateTeamRequest\x1a .authlayer.v1.CreateTeamResponse\x12F\n" +
	"\aGetTeam\x12\x1c.authlayer.v1.GetTeamRequest\x1a\x1d.authlayer.v1.GetTeamResponse\x12O\n" +
	"\n" +
	"UpdateTeam\x12\x1f.authlayer.v1.UpdateTeamRequest\x1a .authlayer.v1.UpdateTeamResponse\x12O\n" +
	"\n" +
	"DeleteTeam\x12\x1f.authlayer.v1.DeleteTeamRequest\x1a .authlayer.v1.DeleteTeamResponse\x12L\n" +
	"\tListTeams\x12\x1e.authlayer.v1.ListTeamsRequest\x1a\x1f.authlayer.v1.ListTeamsResponse\x12T\n" +
	"\tAddMember\x12\".authlayer.v1.AddTeamMemberRequest\x1a#.authlayer.v1.AddTeamMemberResponse\x12]\n" +
	"\fRemoveMember\x12%.authlayer.v1.RemoveTeamMemberRequest\x1a&.authlayer.v1.RemoveTeamMemberResponse\x12Z\n" +
	"\vListMembers\x12$.authlayer.v1.ListTeamMembersRequest\x1a%.authlayer.v1.ListTeamMembersResponseBJZHgithub.com/bernardoforcillo/authlayer/pkg/proto/authlayer/v1;authlayerv1b\x06proto3"

var (
	file_authlayer_v1_team_proto_rawDescOnce sync.Once
	file_authlayer_v1_team_proto_rawDescData []byte
)

func file_authlayer_v1_team_proto_rawDescGZIP() []byte {
	file_authlayer_v1_team_proto_rawDescOnce.Do(func() {
		file_authlayer_v1_team_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authlayer_v1_team_proto_rawDesc), len(file_authlayer_v1_team_proto_rawDesc)))
	})
	return file_authlayer_v1_team_proto_rawDescData
}

var file_authlayer_v1_team_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_authlayer_v1_team_proto_goTypes = []any{
	(*TeamInfo)(nil),                 // 0: authlayer.v1.TeamInfo
	(*CreateTeamRequest)(nil),        // 1: authlayer.v1.CreateTeamRequest
	(*CreateTeamResponse)(nil),       // 2: authlayer.v1.CreateTeamResponse
	(*GetTeamRequest)(nil),           // 3: authlayer.v1.GetTeamRequest
	(*GetTeamResponse)(nil),          // 4: authlayer.v1.GetTeamResponse
	(*UpdateTeamRequest)(nil),        // 5: authlayer.v1.UpdateTeamRequest
	(*UpdateTeamResponse)(nil),       // 6: authlayer.v1.UpdateTeamResponse
	(*DeleteTeamRequest)(nil),        // 7: authlayer.v1.DeleteTeamRequest
	(*DeleteTeamResponse)(nil),       // 8: authlayer.v1.DeleteTeamResponse
	(*ListTeamsRequest)(nil),         // 9: authlayer.v1.ListTeamsRequest
	(*ListTeamsResponse)(nil),        // 10: authlayer.v1.ListTeamsResponse
	(*AddTeamMemberRequest)(nil),     // 11: authlayer.v1.AddTeamMemberRequest
	(*AddTeamMemberResponse)(nil),    // 12: authlayer.v1.AddTeamMemberResponse
	(*RemoveTeamMemberRequest)(nil),  // 13: authlayer.v1.RemoveTeamMemberRequest
	(*RemoveTeamMemberResponse)(nil), // 14: authlayer.v1.RemoveTeamMemberResponse
	(*ListTeamMembersRequest)(nil),   // 15: authlayer.v1.ListTeamMembersRequest
	(*ListTeamMembersResponse)(nil),  // 16: authlayer.v1.ListTeamMembersResponse
	(*PaginationRequest)(nil),        // 17: authlayer.v1.PaginationRequest
	(*PaginationResponse)(nil),       // 18: authlayer.v1.PaginationResponse
	(*MemberInfo)(nil),               // 19: authlayer.v1.MemberInfo
}
var file_authlayer_v1_team_proto_depIdxs = []int32{
	0,  // 0: authlayer.v1.CreateTeamResponse.team:type_name -> authlayer.v1.TeamInfo
	0,  // 1: authlayer.v1.GetTeamResponse.team:type_name -> authlayer.v1.TeamInfo
	0,  // 2: authlayer.v1.UpdateTeamResponse.team:type_name -> authlayer.v1.TeamInfo
	17, // 3: authlayer.v1.ListTeamsRequest.pagination:type_name -> authlayer.v1.PaginationRequest
	0,  // 4: authlayer.v1.ListTeamsResponse.teams:type_name -> authlayer.v1.TeamInfo
	18, // 5: authlayer.v1.ListTeamsResponse.pagination:type_name -> authlayer.v1.PaginationResponse
	17, // 6: authlayer.v1.ListTeamMembersRequest.pagination:type_name -> authlayer.v1.PaginationRequest
	19, // 7: authlayer.v1.ListTeamMembersResponse.members:type_name -> authlayer.v1.MemberInfo
	18, // 8: authlayer.v1.ListTeamMembersResponse.pagination:type_name -> authlayer.v1.PaginationResponse
	1,  // 9: authlayer.v1.TeamService.CreateTeam:input_type -> authlayer.v1.CreateTeamRequest
	3,  // 10: authlayer.v1.TeamService.GetTeam:input_type -> authlayer.v1.GetTeamRequest
	5,  // 11: authlayer.v1.TeamService.UpdateTeam:input_type -> authlayer.v1.UpdateTeamRequest
	7,  // 12: authlayer.v1.TeamService.DeleteTeam:input_type -> authlayer.v1.DeleteTeamRequest
	9,  // 13: authlayer.v1.TeamService.ListTeams:input_type -> authlayer.v1.ListTeamsRequest
	11, // 14: authlayer.v1.TeamService.AddMember:input_type -> authlayer.v1.AddTeamMemberRequest
	13, // 15: authlayer.v1.TeamService.RemoveMember:input_type -> authlayer.v1.RemoveTeamMemberRequest
	15, // 16: authlayer.v1.TeamService.ListMembers:input_type -> authlayer.v1.ListTeamMembersRequest
	2,  // 17: authlayer.v1.TeamService.CreateTeam:output_type -> authlayer.v1.CreateTeamResponse
	4,  // 18: authlayer.v1.TeamService.GetTeam:output_type -> authlayer.v1.GetTeamResponse
	6,  // 19: authlayer.v1.TeamService.UpdateTeam:output_type -> authlayer.v1.UpdateTeamResponse
	8,  // 20: authlayer.v1.TeamService.DeleteTeam:output_type -> authlayer.v1.DeleteTeamResponse
	10, // 21: authlayer.v1.TeamService.ListTeams:output_type -> authlayer.v1.ListTeamsResponse
	12, // 22: authlayer.v1.TeamService.AddMember:output_type -> authlayer.v1.AddTeamMemberResponse
	14, // 23: authlayer.v1.TeamService.RemoveMember:output_type -> authlayer.v1.RemoveTeamMemberResponse
	16, // 24: authlayer.v1.TeamService.ListMembers:output_type -> authlayer.v1.ListTeamMembersResponse
	17, // [17:25] is the sub-list for method output_type
	9,  // [9:17] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_authlayer_v1_team_proto_init() }
func file_authlayer_v1_team_proto_init() {
	if File_authlayer_v1_team_proto != nil {
		return
	}
	file_authlayer_v1_common_proto_init()
	file_authlayer_v1_team_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authlayer_v1_team_proto_rawDesc), len(file_authlayer_v1_team_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authlayer_v1_team_proto_goTypes,
		DependencyIndexes: file_authlayer_v1_team_proto_depIdxs,
		MessageInfos:      file_authlayer_v1_team_proto_msgTypes,
	}.Build()
	File_authlayer_v1_team_proto = out.File
	file_authlayer_v1_team_proto_goTypes = nil
	file_authlayer_v1_team_proto_depIdxs = nil
}
