// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: authlayer/v1/user.proto

package authlayerv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_authlayer_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_authlayer_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Avatar        *string                `protobuf:"bytes,3,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_authlayer_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateUserRequest) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_authlayer_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_authlayer_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_authlayer_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_user_proto_rawDescGZIP(), []int{5}
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PaginationRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Search        *string                `protobuf:"bytes,2,opt,name=search,proto3,oneof" json:"search,omitempty"`
	Status        *UserStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=authlayer.v1.UserStatus,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_authlayer_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *ListUsersRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListUsersRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *ListUsersRequest) GetStatus() UserStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return UserStatus_USER_STATUS_UNSPECIFIED
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserInfo            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_authlayer_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *ListUsersResponse) GetUsers() []*UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ChangePasswordRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CurrentPassword string                 `protobuf:"bytes,1,opt,name=current_password,json=currentPassword,proto3" json:"current_password,omitempty"`
	NewPassword     string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_authlayer_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *ChangePasswordRequest) GetCurrentPassword() string {
	if x != nil {
		return x.CurrentPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ChangePasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordResponse) Reset() {
	*x = ChangePasswordResponse{}
	mi := &file_authlayer_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordResponse) ProtoMessage() {}

func (x *ChangePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authlayer_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordResponse.ProtoReflect.Descriptor instead.
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return file_authlayer_v1_user_proto_rawDescGZIP(), []int{9}
}

var File_authlayer_v1_user_proto protoreflect.FileDescriptor

const file_authlayer_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x17authlayer/v1/user.proto\x12\fauthlayer.v1\x1a\x19authlayer/v1/common.proto\x1a\x1cgoogle/api/annotations.proto\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"=\n" +
	"\x0fGetUserResponse\x12*\n" +
	"\x04user\x18\x01 \x01(\v2\x16.authlayer.v1.UserInfoR\x04user\"v\n" +
	"\x11UpdateUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1b\n" +
	"\x06avatar\x18\x03 \x01(\tH\x01R\x06avatar\x88\x01\x01B\a\n" +
	"\x05_nameB\t\n" +
	"\a_avatar\"@\n" +
	"\x12UpdateUserResponse\x12*\n" +
	"\x04user\x18\x01 \x01(\v2\x16.authlayer.v1.UserInfoR\x04user\",\n" +
	"\x11DeleteUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x14\n" +
	"\x12DeleteUserResponse\"\xbd\x01\n" +
	"\x10ListUsersRequest\x12?\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1f.authlayer.v1.PaginationRequestR\n" +
	"pagination\x12\x1b\n" +
	"\x06search\x18\x02 \x01(\tH\x00R\x06search\x88\x01\x01\x125\n" +
	"\x06status\x18\x03 \x01(\x0e2\x18.authlayer.v1.UserStatusH\x01R\x06status\x88\x01\x01B\t\n" +
	"\a_searchB\t\n" +
	"\a_status\"\x83\x01\n" +
	"\x11ListUsersResponse\x12,\n" +
	"\x05users\x18\x01 \x03(\v2\x16.authlayer.v1.UserInfoR\x05users\x12@\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2 .authlayer.v1.PaginationResponseR\n" +
	"pagination\"e\n" +
	"\x15ChangePasswordRequest\x12)\n" +
	"\x10current_password\x18\x01 \x01(\tR\x0fcurrentPassword\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"\x18\n" +
	"\x16ChangePasswordResponse2\xb1\x04\n" +
	"\vUserService\x12c\n" +
	"\aGetUser\x12\x1c.authlayer.v1.GetUserRequest\x1a\x1d.authlayer.v1.GetUserResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/users/{user_id}\x12o\n" +
	"\n" +
	"UpdateUser\x12\x1f.authlayer.v1.UpdateUserRequest\x1a .authlayer.v1.UpdateUserResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*2\x13/v1/users/{user_id}\x12l\n" +
	"\n" +
	"DeleteUser\x12\x1f.authlayer.v1.DeleteUserRequest\x1a .authlayer.v1.DeleteUserResponse\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/v1/users/{user_id}\x12_\n" +
	"\tListUsers\x12\x1e.authlayer.v1.ListUsersRequest\x1a\x1f.authlayer.v1.ListUsersResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/users\x12}\n" +
	"\x0eChangePassword\x12#.authlayer.v1.ChangePasswordRequest\x1a$.authlayer.v1.ChangePasswordResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/users/me/passwordBJZHgithub.com/bernardoforcillo/authlayer/pkg/proto/authlayer/v1;authlayerv1b\x06proto3"

var (
	file_authlayer_v1_user_proto_rawDescOnce sync.Once
	file_authlayer_v1_user_proto_rawDescData []byte
)

func file_authlayer_v1_user_proto_rawDescGZIP() []byte {
	file_authlayer_v1_user_proto_rawDescOnce.Do(func() {
		file_authlayer_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authlayer_v1_user_proto_rawDesc), len(file_authlayer_v1_user_proto_rawDesc)))
	})
	return file_authlayer_v1_user_proto_rawDescData
}

var file_authlayer_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_authlayer_v1_user_proto_goTypes = []any{
	(*GetUserRequest)(nil),         // 0: authlayer.v1.GetUserRequest
	(*GetUserResponse)(nil),        // 1: authlayer.v1.GetUserResponse
	(*UpdateUserRequest)(nil),      // 2: authlayer.v1.UpdateUserRequest
	(*UpdateUserResponse)(nil),     // 3: authlayer.v1.UpdateUserResponse
	(*DeleteUserRequest)(nil),      // 4: authlayer.v1.DeleteUserRequest
	(*DeleteUserResponse)(nil),     // 5: authlayer.v1.DeleteUserResponse
	(*ListUsersRequest)(nil),       // 6: authlayer.v1.ListUsersRequest
	(*ListUsersResponse)(nil),      // 7: authlayer.v1.ListUsersResponse
	(*ChangePasswordRequest)(nil),  // 8: authlayer.v1.ChangePasswordRequest
	(*ChangePasswordResponse)(nil), // 9: authlayer.v1.ChangePasswordResponse
	(*UserInfo)(nil),               // 10: authlayer.v1.UserInfo
	(*PaginationRequest)(nil),      // 11: authlayer.v1.PaginationRequest
	(UserStatus)(0),                // 12: authlayer.v1.UserStatus
	(*PaginationResponse)(nil),     // 13: authlayer.v1.PaginationResponse
}
var file_authlayer_v1_user_proto_depIdxs = []int32{
	10, // 0: authlayer.v1.GetUserResponse.user:type_name -> authlayer.v1.UserInfo
	10, // 1: authlayer.v1.UpdateUserResponse.user:type_name -> authlayer.v1.UserInfo
	11, // 2: authlayer.v1.ListUsersRequest.pagination:type_name -> authlayer.v1.PaginationRequest
	12, // 3: authlayer.v1.ListUsersRequest.status:type_name -> authlayer.v1.UserStatus
	10, // 4: authlayer.v1.ListUsersResponse.users:type_name -> authlayer.v1.UserInfo
	13, // 5: authlayer.v1.ListUsersResponse.pagination:type_name -> authlayer.v1.PaginationResponse
	0,  // 6: authlayer.v1.UserService.GetUser:input_type -> authlayer.v1.GetUserRequest
	2,  // 7: authlayer.v1.UserService.UpdateUser:input_type -> authlayer.v1.UpdateUserRequest
	4,  // 8: authlayer.v1.UserService.DeleteUser:input_type -> authlayer.v1.DeleteUserRequest
	6,  // 9: authlayer.v1.UserService.ListUsers:input_type -> authlayer.v1.ListUsersRequest
	8,  // 10: authlayer.v1.UserService.ChangePassword:input_type -> authlayer.v1.ChangePasswordRequest
	1,  // 11: authlayer.v1.UserService.GetUser:output_type -> authlayer.v1.GetUserResponse
	3,  // 12: authlayer.v1.UserService.UpdateUser:output_type -> authlayer.v1.UpdateUserResponse
	5,  // 13: authlayer.v1.UserService.DeleteUser:output_type -> authlayer.v1.DeleteUserResponse
	7,  // 14: authlayer.v1.UserService.ListUsers:output_type -> authlayer.v1.ListUsersResponse
	9,  // 15: authlayer.v1.UserService.ChangePassword:output_type -> authlayer.v1.ChangePasswordResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_authlayer_v1_user_proto_init() }
func file_authlayer_v1_user_proto_init() {
	if File_authlayer_v1_user_proto != nil {
		return
	}
	file_authlayer_v1_common_proto_init()
	file_authlayer_v1_user_proto_msgTypes[2].OneofWrappers = []any{}
	file_authlayer_v1_user_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authlayer_v1_user_proto_rawDesc), len(file_authlayer_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authlayer_v1_user_proto_goTypes,
		DependencyIndexes: file_authlayer_v1_user_proto_depIdxs,
		MessageInfos:      file_authlayer_v1_user_proto_msgTypes,
	}.Build()
	File_authlayer_v1_user_proto = out.File
	file_authlayer_v1_user_proto_goTypes = nil
	file_authlayer_v1_user_proto_depIdxs = nil
}
